### ISSUE TITLE
Import and Export Entire Profile

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Account-Manager#149]

**Comment by sno2** [comment]
The GUI could look roughly like this (with my amazing artistic ability included for free):

![image](https://user-images.githubusercontent.com/43641633/98841951-71a96100-240e-11eb-8d28-59651887bb86.png)

When you click the Load File button, the content of the file selected from the file picker would be injected into the signing key form input.  We could also maybe set the nickname as the name of the file, but that would need debate.
