### ISSUE TITLE
Toast

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Account-Manager#232]
**Successfully creating an account**
https://www.figma.com/file/T7h0e42BUUZyuiZj9HXv7w/Side-Menu-Functions?node-id=141%3A1837

**Sending points**
https://www.figma.com/file/M4wHv7B4JNig3bH2cywI9u/Accounts?node-id=376%3A4373

<img width="627" alt="Screen Shot 2020-08-28 at 4 18 36 PM" src="https://user-images.githubusercontent.com/8547538/91622013-2670cd80-e94a-11ea-8524-d95648fe66b4.png">

**Comment by leelatanniru** [comment]
Could you please assign this to me. I would like to work on this.
