### ISSUE TITLE
App crashes when attempting to edit the nickname of a non-managed/friend accounts

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Account-Manager#244]
App crashes when attempting to edit the nickname of a non-managed/friend account. This option should not be available in the 3 dot menu on those account pages. 

<img width="1205" alt="Screen Shot 2020-09-02 at 5 21 28 PM" src="https://user-images.githubusercontent.com/8547538/92050019-d4acb680-ed40-11ea-9d02-ab6342f1e06e.png">

**Comment by leelatanniru** [comment]
I tried reproducing this issue by updating the Nickname of friend account, the name was updated successfully. I am not able to reproduce this bug. Is there any specific case for this issue to occur?
