### ISSUE TITLE
When points are sent to friend the from sender account balance should get reduced

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#296]
**Bug Description**
When points are sent to friend the from sender account balance should get reduced

**Steps to Reproduce**
1. Go to friend overview window
2. Click on "Send Points
3. Send points to desired friend
4. Check balance at Submitter

**Actual Result**
Balance is not deducted when points are sent

**Expected Result**
When points are sent to friend the from sender account balance should get reduced

**OS version**
Windows

**Screenshot/Recording**
https://recordit.co/IetQIdkrAL

**Comment by buckyroberts** [comment]
Should be fixed
