### ISSUE TITLE
No option available to logout and again login to app with same account

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#297]
**Bug Description**
No option available to logout and again login to app with same account

**Steps to Reproduce**
1. Click on Log off icon on at top right corner
2. Only reset option is displayed

**Actual Result**
No option available to logout and again login to app with same account

**Expected Result**
When user clicks on log off button it should display two option 1. Reset Account 2. Logout from app
And when user log out user should have login option with same account 

**OS version**
Windows

**Screenshot/Recording**
![image](https://user-images.githubusercontent.com/59204822/93567329-19288b00-f9ac-11ea-91e0-49ba5fcd3832.png)

**Comment by buckyroberts** [comment]
This is part of the import/export profile discussion.
