### ISSUE TITLE
When friend is removed information for friend remains as it is

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#298]
**Bug Description**
When friend is removed information for friend remains as it is

**Steps to Reproduce**
1. Go to friend overview window
2. Click on three dots at top right corner
3. Click on Remove friend
4. See result

**Actual Result**
When friend is removed information for friend remains as it is

**Expected Result**
Information should be removed

**OS version**
Windows

**Screenshot/Recording**
http://recordit.co/XlwstQYl4f

**Comment by kristykjlee** [comment]
This has been moved to the Design Repository
