### ISSUE TITLE
No notification received when points sent or received

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#299]
**Bug Description**
No notification received when points send or received

**Steps to Reproduce**
1. Send or received point 
2. Check notification

**Actual Result**
No notification received when points send or received

**Expected Result**
When points are sent or received no notification is there

**OS version**
Windows

**Screenshot/Recording**
![image](https://user-images.githubusercontent.com/59204822/93578816-6829ec80-f9bb-11ea-9c2a-83e3cc86f1a9.png)

**Comment by camapantap** [comment]
> **Mô tả lỗi**
> Không nhận được thông báo khi gửi hoặc nhận điểm
> 
> **Các bước để tạo lại**
> 
> 1. Gửi hoặc nhận điểm
> 2. Kiểm tra thông báo
> 
> **Kết quả thực tế**
> Không nhận được thông báo khi điểm gửi hoặc nhận
> 
> **Kết quả mong đợi**
> Khi điểm được gửi hoặc nhận không có thông báo
> 
> **Phiên bản hệ điều hành**
> Windows
> 
> **Ảnh chụp màn hình / Ghi âm**
> ![hình ảnh](https://user-images.githubusercontent.com/59204822/93578816-6829ec80-f9bb-11ea-9c2a-83e3cc86f1a9.png)

Dich

**Comment by camapantap** [comment]
@ #

> `
Duplicate of #`

**Comment by buckyroberts** [comment]
Closing as this is related to that larger active confirmation services issue - https://github.com/thenewboston-developers/Account-Manager/issues/296
