### ISSUE TITLE
[As per document] Bank fee should be Two Points

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#300]
**Bug Description**
Bank fee should be Two Points

**Steps to Reproduce**
1. Go to Send Points
2. In resulting popup check "Bank fee"

**Actual Result**
Bank fee is 1 point

**Expected Result**
[As per document] Bank fee should be Two Points

**OS version**
Windows

**Screenshot**
![image](https://user-images.githubusercontent.com/59204822/93660538-b0094c00-fa6d-11ea-91cc-ec3b49164d96.png)
![image](https://user-images.githubusercontent.com/59204822/93660546-beeffe80-fa6d-11ea-9f40-6e3fbee7f3fc.png)

**Comment by Niekon01** [comment]
"Lastly, banks will collect transaction fees from all blocks sent through them. The transaction fees are determined by the individual banks. This will give users the ability to choose banks with the most reliable service and who offer the lowest transaction fees."

It does have to be 2. Banks can decide the transaction fees for themselves.
