### ISSUE TITLE
When user1 add user2 as a friend then in user2 friend's list name of user1 should be displayed

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#304]
**Bug Description**
When user1 add user2 as a friend then in user2 friend's list name of user1 is not displayed 

**Steps to Reproduce**
1. Add user2 as a friend of user1
2. Go to user2 check friend list
3. user1 name not displayed

**Actual Result**
When user1 add user2 as a friend then in user2 friend's list name of user1 is not displayed 

**Expected Result**
When user1 add user2 as a friend then in user2 friend's list name of user1 should be displayed

**OS version**
Windows

**Comment by Niekon01** [comment]
This does not need to happen. If people you don't know add you as a friend, you friends list will be full of accounts and people unknown to you.

**Comment by kristykjlee** [comment]
This has been moved to the Design Repository
