### ISSUE TITLE
[Desktop Windows] While sending point then in "To" list sender name should not be displayed

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#317]
**Bug Description**
 While sending point then in "To" list sender name  displayed

**Steps to Reproduce**
1. Click on "Send Points" button
2. In resulting module check list of "To" users

**Expected behavior**
 While sending point then in "To" list sender name should not be displayed

**Actual behavior**
 While sending point then in "To" list sender name  displayed

**Screenshots/Recordings**
![image](https://user-images.githubusercontent.com/59204822/93981995-4c995a00-fd9e-11ea-8468-cee136149482.png)

**OS and Browser**
 - OS: [e.g. Windows 7]

**Additional context**
App version : v1.0.0-alpha.16

**Account Number**
15e164325715c9552911caf7e3ea1759f4c2ccba5fd82864a4d811d67935c4f9

**Comment by buckyroberts** [comment]
Closing. This was an intentional design to allow to user to switch easier (without having to deselect the first option)
