### ISSUE TITLE
How can I contribute to this project?

### ISSUE THREAD

**Issue by amrsekilly** [thenewboston-developers/Account-Manager#32]
Hi,

I have a full-time job, but I'm interested in contributing to this project part-time. I'm experienced in React and Redux. And I got the app running locally. 

Let me know how I can help by assigning me some tickets.

<img width="1680" alt="Screenshot 2020-07-13 07 47 56" src="https://user-images.githubusercontent.com/4142276/87274892-2cffce80-c4dd-11ea-8b0a-475ccfaf6aaa.png">

**Comment by angle943** [comment]
hey @amrsekilly , great to have a fellow react/redux developer! 

As you can probably tell, the app is still in a very infantile state. I am getting some of the basic thing done, but I should be ready to be creating tickets soon.

Do you have experience working with an electron app?

**Comment by amrsekilly** [comment]
@angle943 Thanks!

I've never used Electron at work, but I've used it to build simple personal projects in the past. That's one of the reasons I wanna contribute to the project, to gain more experience working with Electron.

**Comment by angle943** [comment]
fantastic! We already have a couple issues I've posted, feel free to grab any and try them out! I'll be releasing bigger tickets soon
