### ISSUE TITLE
[Desktop Windows] When user change active bank it takes to much time 

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#320]
**Bug Description**
When user change active bank it takes to much time 

**Steps to Reproduce**
1. Click on 'Change active bank'.
2. Enter details 

**Expected behavior**
When user change active bank it takes to much time 

**Actual behavior**
Selected bank should be set as active bank 

**Screenshots/Recordings**
https://recordit.co/u13fTfIpnF

**OS and Browser**
 OS: [Windows 7]

**Account Number**
15e164325715c9552911caf7e3ea1759f4c2ccba5fd82864a4d811d67935c4f9

**Comment by buckyroberts** [comment]
Related to old bug causing infinite loop to fetch configs.
