### ISSUE TITLE
[Desktop Windows] Unable to do any transaction 

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#322]
**Bug Description**
When user try to do transaction between My accounts error message is displayed

**Steps to Reproduce**
1. Go to "My accounts"
2. Select of the account
3. Send points from one account to another account

**Expected behavior**
User should be able to send points

**Actual behavior**
When user try to do transaction between My accounts error message is displayed

**Screenshots/Recordings**
http://recordit.co/R4Y267lobY
![image](https://user-images.githubusercontent.com/59204822/94115778-d6612a00-fe67-11ea-8370-b8474cb681b9.png)

**OS and Browser**
 - OS: [Windows 7]

**Additional context**
App version : v1.0.0-alpha.16

**Account Number**
15e164325715c9552911caf7e3ea1759f4c2ccba5fd82864a4d811d67935c4f9

**Comment by buckyroberts** [comment]
Bug should be fixed now.

**Comment by webdeveloperswj** [comment]
Issue solved
