### ISSUE TITLE
[Windows] Bank fee showing different for banks

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#327]
**Bug Description**
Bank fee showing different for banks

**Steps to Reproduce**
1. Go to  Add Banks
2. Add two banks
3. Check bank fee while sending opoints

**Expected behavior**
Bank fee should be same

**Actual behavior**
Bank fee showing different for banks

**Screenshots/Recordings**
1. 
![image](https://user-images.githubusercontent.com/59204822/94235506-513e4980-ff29-11ea-8a83-900d7c2a6ba4.png)

2. 
![image](https://user-images.githubusercontent.com/59204822/94235564-67e4a080-ff29-11ea-83ec-714fd3ffbdad.png)

**OS and Browser**
 - OS: [Windows 7]

**Additional context**
 App version : v1.0.0-alpha.18

**Account Number**
15e164325715c9552911caf7e3ea1759f4c2ccba5fd82864a4d811d67935c4f9

**Comment by buckyroberts** [comment]
Banks are allowed to have different fees.
