### ISSUE TITLE
[Windows desktop] Console error

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#328]
**1. While app is force reload** 
![image](https://user-images.githubusercontent.com/59204822/94236920-9ebbb600-ff2b-11ea-975c-a427c7f47cb7.png)

**2. This error occurs rarely while navigating through app** 
![image](https://user-images.githubusercontent.com/59204822/94237752-f6a6ec80-ff2c-11ea-975a-19c466db7e1f.png)

**Comment by brian316** [comment]
Are we going to enable hot reload (refresh) on the production application? I don't think that sounds like a good idea and you can only do that when enabling dev tools. Is the 'toggledevtools' option going to be enabled in the final version?

**Comment by jeremygblake** [comment]
I could try to take a look at the second error.  Seems like you need a "wait for mount" before you call the useEffect function.

**Comment by itsnikhil** [comment]
Can anyone link to merged PR addressing this issue and account for payment
