### ISSUE TITLE
Accounts Page UI Updates

### ISSUE THREAD

**Issue by angle943** [thenewboston-developers/Account-Manager#33]
Figma links for reference: https://www.figma.com/file/M4wHv7B4JNig3bH2cywI9u/Accounts?node-id=46%3A814

This page mainly entails UI update. 

![Screen Shot 2020-07-13 at 7 56 54 PM](https://user-images.githubusercontent.com/5943963/87378639-14c29a80-c543-11ea-988e-0c434fa44c07.png)

1 ) update the styling in our app to make it look like this as close as possible
2 ) Add the `DropDownMenuButton` with only the `Edit` and `Delete Account` options (no `Unregister Bank`).
3 ) `Edit`  should do nothing (you can just use lodash's `noop` function for their `onClick` event). When you click `Delete Account`, make the modal show up that's shown in the figma mocks. (Clicking `Yes`, however, will currently do nothing)

Any questions you have, feel free to ask me any time :D

**Comment by sidou01** [comment]
Hi, I am going to submit a PR for this.

**Comment by Hristijan95** [comment]
Ahh, I've just created a PR for this and saw that @sidou01 created one before me.
