### ISSUE TITLE
[Windows] User is not able to add bank 

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#330]
**Bug Description**
User is not able to add bank 

**Steps to Reproduce**
1. Go to "Banks"
2.  Add bank

**Expected behavior**
User is not able to add bank. 

**Actual behavior**
User Should be able to add banks

**Screenshots/Recordings**
https://recordit.co/wwdrNLzqiA

**OS and Browser**
 OS: [Windows 7]

**Account Number**
15e164325715c9552911caf7e3ea1759f4c2ccba5fd82864a4d811d67935c4f9

**Comment by avgust13** [comment]
@webdeveloperswj you are trying to add bank which is offline, app shows only Toast message "timeout 5000ms exceeded". @buckyroberts should we handle this scenario with additional validation message on the form itself?

**Comment by kristykjlee** [comment]
This has been moved to the Design Repository
