### ISSUE TITLE
[Windows] After each transcation there is an extra entry of one transcation

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#331]
**Bug Description**
When user send points to friends then in transactions there is an extra entry 

**Steps to Reproduce**
1. Go to My accounts >>Transaction

**Expected behavior**
Only that entry should be displayed.

**Actual behavior**
Extra one entry is displayed.

**Screenshots/Recordings**
https://recordit.co/s7alf6haoh

**OS and Browser**
 OS: [Windows 7]

**Account Number**
15e164325715c9552911caf7e3ea1759f4c2ccba5fd82864a4d811d67935c4f9

**Comment by buckyroberts** [comment]
@kristykjlee these are the Tx fees that you pay to the Bank and Validator. We should think of a better way to indicate that those are fees.

**Comment by Ramin-RX7** [comment]
@buckyroberts is it possible to add a column to each transaction and display those Tx fees there
like this: [https://ibb.co/583m469](TxFees)

**Comment by kristykjlee** [comment]
This has been moved to the Design Repository
