### ISSUE TITLE
[Windows] User should not be able to add himself as friend

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#337]
**Bug Description**
User is able to add himself as friend

**Steps to Reproduce**
1. Go to "Add friend"
2. Add yourself as friend

**Expected behavior**
User should not be able to add himself as friend

**Actual behavior**
User is able to add himself as friend

**Screenshots/Recordings**
http://recordit.co/RUsOfHj7UE

**OS and Browser**
 - OS: [Windows 7]

**Additional context**
App version 19

**Account Number**
15e164325715c9552911caf7e3ea1759f4c2ccba5fd82864a4d811d67935c4f9

**Comment by avgust13** [comment]
@buckyroberts do I show validation message or just disable Add button when account number matches with my?

**Comment by buckyroberts** [comment]
@avgust13 let's go with this error message and disable the button as well.

<img width="427" alt="Screen Shot 2020-09-29 at 8 47 53 PM" src="https://user-images.githubusercontent.com/8547538/94641057-132c8700-0295-11eb-9404-596d7602b159.png">

**Comment by webdeveloperswj** [comment]
Issue solved 
![image](https://user-images.githubusercontent.com/59204822/95041171-96b20200-06f3-11eb-8e08-031003be62fa.png)
