### ISSUE TITLE
[Desktop] Hovered option should highlighted

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#338]
**Bug Description**
When clicked on three dots on top right corner selected hovered and not selected  option also get highlighted 

**Steps to Reproduce**
1. Go to any one of module
2. Click on three dots at top right corner

**Expected behavior**
Only hovered option should get highlighted

**Actual behavior**
When clicked on three dots on top right corner selected hovered and not selected  option also get highlighted 

**Screenshots/Recordings**
http://recordit.co/D9jXVf33Wh

**OS and Browser**
 - OS: [e.g. Windows 7]

**Additional context**
App version alpha.19

**Account Number**
15e164325715c9552911caf7e3ea1759f4c2ccba5fd82864a4d811d67935c4f9

**Comment by angle943** [comment]
Added a "Design" tag to this issue. This is not a bug. We need a UI distinction between a focused option and a hovered option.

**Comment by kristykjlee** [comment]
This has been moved to the Design Repository
