### ISSUE TITLE
[Desktop] While sending points, Point should not accept decimal values

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#339]
**Bug Description**
While sending points, Point should not accept decimal values

**Steps to Reproduce**
1. Go to 'Send Points" modules
2. Enter Points in decimal
3. Click on "Send" button

**Expected behavior**
While sending points, Point should not accept decimal values

**Actual behavior**
While sending points, Point accept decimal values

**Screenshots/Recordings**
http://recordit.co/MV99CLvCuW

**OS and Browser**
 - OS: [e.g. Windows 7]

**Additional context**
App version alpha 19

**Account Number**
15e164325715c9552911caf7e3ea1759f4c2ccba5fd82864a4d811d67935c4f9

**Comment by tpikachu** [comment]
Lined Issue: https://github.com/thenewboston-developers/Account-Manager/issues/339

**Comment by webdeveloperswj** [comment]
Issue solved 
![image](https://user-images.githubusercontent.com/59204822/95041081-4e92df80-06f3-11eb-9e35-5e7090727433.png)
