### ISSUE TITLE
[Desktop] Notification text can be improved when points are received

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#340]
**Bug Description**
When points are received notification text is "Account number/Account Name Paid You User Account Name"

**Steps to Reproduce**
1. Go to Notification list
2. Check notification text for received text

**Expected behavior**
When points are received notification text is "Account number/Account Name Sent You Points on User Account Name Account"
e.g, "Snehal sent you points on Demo1 account"

**Actual behavior**
When points are received notification text is "Account number/Account Name Paid You User Account Name"

**Screenshots/Recordings**
![image](https://user-images.githubusercontent.com/59204822/94431514-06cffd80-01b3-11eb-9b14-5684257b122d.png)

**OS and Browser**
 - OS: [Windows 7]

**Additional context**
App Version Alpha 19

**Account Number**
15e164325715c9552911caf7e3ea1759f4c2ccba5fd82864a4d811d67935c4f9

**Comment by nsushman** [comment]
When the Amount Received is around 7 digits or more, would there be an overlap?

I was trying to simulate this text in the Figma and had to reduce two characters when the message and the amount are pretty long.
![image](https://user-images.githubusercontent.com/18399270/98459695-2a7b6000-21c3-11eb-9b38-f540442d307e.png)

@webdeveloperswj

**Comment by kristykjlee** [comment]
This has been moved to the Design Repository
