### ISSUE TITLE
[MAC OS] No notification displayed when points are received

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#342]
**Bug Description**
No notification displayed when points are received

**Steps to Reproduce**
1. Receive points from user
2. Check notification

**Expected behavior**
Notification should be received when points are received

**Actual behavior**
No notification displayed when points are received

**Screenshots/Recordings**
![image](https://user-images.githubusercontent.com/59204822/94549998-abfcdb80-0270-11eb-9a9f-07e64ec91049.png)

**OS and Browser**
 - OS: [OS MACBOOK  PRO]

**Additional context**
App Version Alpha 19

**Account Number**
15e164325715c9552911caf7e3ea1759f4c2ccba5fd82864a4d811d67935c4f9

**Comment by buckyroberts** [comment]
Same issue as another ticket. Closing.
