### ISSUE TITLE
[Windows] Add Search functionality to "Transaction" and "Accounts" table

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#346]
![image](https://user-images.githubusercontent.com/59204822/94558009-06039e00-027d-11eb-83c0-b1c5ff6b71ea.png)
![image](https://user-images.githubusercontent.com/59204822/94558049-0dc34280-027d-11eb-93e0-fbbc949a7d94.png)
![image](https://user-images.githubusercontent.com/59204822/94558510-9215c580-027d-11eb-99b2-ac759ac74814.png)

**Comment by georgeiliadis91** [comment]
I have implemented a solution but quite find the styling / placement for such thing on figma. Let me know when its done so i make a PR.
