### ISSUE TITLE
Up/down arrows should work even after focusing on a disabled option

### ISSUE THREAD

**Issue by angle943** [thenewboston-developers/Account-Manager#349]
![Screen Shot 2020-09-29 at 10 17 45 PM](https://user-images.githubusercontent.com/5943963/94645950-f6e31700-02a1-11eb-9206-ba366443ebb7.png)
clicking down to one of the disabled option will make it so that the up/down arrows no longer work. pressing up/down arrows should not be disabled for disabled options, only the 'enter' button should be disabled

**Comment by angle943** [comment]
@hawyar hey what is your account number?

**Comment by hawyar** [comment]
@angle943 0ead156c2d20480aa075ac8450feb158876010a6579c9a6594836e5740e05606

**Comment by angle943** [comment]
@hawyar ah i see your account # is different than the one that's listed on https://thenewboston.com/leaderboard/All

I've sent in a pull request to update your account # to the one you listed above, and I've also sent you 5000 points to your new account #
