### ISSUE TITLE
Accounts -> Send Points Modal (UI)

### ISSUE THREAD

**Issue by angle943** [thenewboston-developers/Account-Manager#35]
![Screen Shot 2020-07-13 at 8 23 06 PM](https://user-images.githubusercontent.com/5943963/87380123-ac75b800-c546-11ea-9f23-d4421374b9ff.png)

figma link: https://www.figma.com/file/M4wHv7B4JNig3bH2cywI9u/Accounts?node-id=46%3A2245

- when clicking `Send Points`, this modal should appear.
- use fake data for the Accounts, friends, account balance. You can use constants for `Bank Registration fee` and `Validator Tx Fee`.
- Make the form not submittable until the required fields are filled out.
- make sure the `TOTAL Tx` calculates correctly based upon the variables that you have
- clicking the `Send` button should just console log the values of the form

**Comment by Hristijan95** [comment]
I've made the points send form, except for the TOTAL Tx calculation because I've never worked with formik, so I need some more time. I had to go, I will finish it tomorrow if no one commits an update until then.

**Comment by angle943** [comment]
https://github.com/thenewboston-developers/Account-Manager/pull/42
