### ISSUE TITLE
No error message displayed when already present Validator is added

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#351]
**Bug Description**
No error message displayed when already present Validator is added

**Steps to Reproduce**
1. Go to "Add Validator"
2. Add already present validator

**Expected behavior**
Error message should be displayed

**Actual behavior**
No error message displayed when already present Validator is added

**Screenshots/Recordings**
http://recordit.co/HHQk50yIL1

**OS and Browser**
 - OS: [e.g. Windows 7]

**Additional context**
App version Alpha 19

**Account Number**
15e164325715c9552911caf7e3ea1759f4c2ccba5fd82864a4d811d67935c4f9

**Comment by avgust13** [comment]
@buckyroberts Error message is ok? "This validator already exists"
