### ISSUE TITLE
Crawl for Banks & Validators

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Account-Manager#356]
### Feature description
An authenticated Bank or Validator will have the option to crawl their own server to make sure the servers data is up to date.

There will be 3 possible "Crawl" statuses.
- **Not Crawling** > Crawl button
- **Crawling status** > Request Stop button
- **Stop Request** > no button

## GET /crawl

**Response**
```json
{
  "crawl_last_completed": "2020-09-04 23:17:48.877648+00:00",
  "crawl_status": "not_crawling"
}
```

## POST /crawl

**Request**
```json
{
  "message": {
    "crawl": "start"
  },
  "node_identifier": "d5356888dc9303e44ce52b1e06c3165a7759b9df1e6a6dfbd33ee1c3df1ab4d1",
  "signature": "c1338eb1792676edc036070548b9be2ae69cd8b2ff87a983402498b89d60b60a74ffaf2495da14a8f2d72bb98eee538472b928e49630c27b2aadf65523a4690b"
}
```

**Response**
```json
{
  "crawl_last_completed": "2020-09-04 23:17:48.877648+00:00",
  "crawl_status": "crawling"
}
```

## WebSocket - ws://[SERVER_ADDRESS]/ws/crawl_status

**Message shape**
```json
{
  "notification_type": "CRAWL_COMPLETED_NOTIFICATION",
  "payload": {
    "crawl_last_completed": "2020-09-04 23:17:48.877648+00:00",
    "crawl_status": "not_crawling"
  }
}
```

### Design notes
- Crawl Status UI will be a block above the Bank's Network ID & Acc#
- Statuses use the colors Sail Red/Green 500

In the near future, we are going to include 'Clean', but that will be for a later ticket. 

### Links
- https://docs.google.com/document/d/1xyIr3Tdw2iqLO2EsNDMCncia1xemSU-QERlBsaPviLY/edit?usp=sharing
- https://www.figma.com/file/ObSUx1rum1MIeZkFT3XIn1/Bank-User?node-id=809%3A0

<img width="1255" alt="Screen Shot 2020-09-30 at 7 13 08 PM" src="https://user-images.githubusercontent.com/8547538/94758054-fd7c9780-0350-11eb-907a-c371dc2dd1b5.png">

**Comment by codacy20** [comment]
hey Bucky, i wanted to pick this one up but i wasn't sure how i can retrieve sample data from backend to build the component. what am i missing?

**Comment by buckyroberts** [comment]
Updated to draft, waiting for BE changes.
