### ISSUE TITLE
Validator Confirmation Service Received Notification

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Account-Manager#358]
**Task**
- Add `VALIDATOR_CONFIRMATION_SERVICE_NOTIFICATION` support to the app
- I included a screenshot of the notification mock below, but I couldn't find the exact text/styling for this specific notification. Check with @kristykjlee for that

WS endpoint:
`ws://143.110.137.54/ws/validator_confirmation_services`

```
{
  "notification_type": "VALIDATOR_CONFIRMATION_SERVICE_NOTIFICATION",
  "payload": {
    "bank_node_identifier": "b1b232503b3db3975524faf98674f22c83f4357c3d946431b8a8568715d7e1d9",
    "validator_confirmation_service": {
      "id": "6c5d1336-4454-454d-96f9-124a9a659cc9",
      "created_date": "2020-10-01T03:39:36.675680Z",
      "modified_date": "2020-10-01T03:39:36.675734Z",
      "end": "2021-06-03T22:15:09.343282Z",
      "start": "2021-06-01T22:15:09.343282Z",
      "validator": "e2a138b0-ebe9-47d2-a146-fb4d9d9ca378"
    }
  }
}
```

<img width="430" alt="Screen Shot 2020-09-30 at 8 44 16 PM" src="https://user-images.githubusercontent.com/8547538/94762927-d7112900-035d-11eb-82bf-09fcd31d0e3b.png">

**Comment by avgust13** [comment]
@kristykjlee do we have firma for this issue?

**Comment by mmmols** [comment]
I would love to give this a shot? 😻

**Comment by kristykjlee** [comment]
@mthomas-io is assigned this ticket and and will be taking charge of it. Don't forget to include your account number onto the ticket so you can get compensated for your efforts.

**Comment by mmmols** [comment]
Okay, let me know if I can help with anything 😊

**Comment by mthomas-io** [comment]
@mmmols [message me on Slack.](https://thenewboston.slack.com/archives/D01E5LL1JV9)
