### ISSUE TITLE
Account Number Link Issue

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Account-Manager#363]
When you:
1. go to a friends page
2. view their transactions
3. click on their account number

it takes you to the overview page, but instead of displaying their nickname it displays the full account number.

<img width="551" alt="Screen Shot 2020-10-02 at 8 10 03 PM" src="https://user-images.githubusercontent.com/8547538/94981956-86c7d180-04eb-11eb-8199-56b8e7961236.png">

<img width="755" alt="Screen Shot 2020-10-02 at 8 10 11 PM" src="https://user-images.githubusercontent.com/8547538/94981957-88919500-04eb-11eb-84e9-d0a719bfdad9.png">

<img width="980" alt="Screen Shot 2020-10-02 at 8 10 19 PM" src="https://user-images.githubusercontent.com/8547538/94981959-892a2b80-04eb-11eb-8481-a3041708ef8e.png">

**Comment by lapstjup** [comment]
#365 submitted a pull request for resolving the navigation from friends to accounts overview on clicking a friend's account link.

**Comment by webdeveloperswj** [comment]
Not Done on Version 22

**Comment by webdeveloperswj** [comment]
@lapstjup Please check same when user clicks on Name notification 
![image](https://user-images.githubusercontent.com/59204822/95451247-25897d80-0985-11eb-81bd-cf82dbf88a49.png)

**Comment by lapstjup** [comment]
@webdeveloperswj I guess @angle943 is working on restructuring the code base and that would probably take care of this issue. Otherwise let me know if this issue is open after code restructure.

**Comment by Hristijan95** [comment]
I am working on this, will submit a PR soon.

**Comment by angle943** [comment]
check out @Hristijan95 's comment and my comment on https://github.com/thenewboston-developers/Account-Manager/pull/434 . That will be an acceptance criteria for this ticket.

This `if` logic that @Hristijan95 describes should not be housed within our `Layout/index.tsx` file (this file should not have any complicated logic), but rather, I think it should be housed in a component that will be a parent of both the `Account` and `Friend` component.

However, if you have a better solution, please discuss with me!

**Comment by angle943** [comment]
resolved with recent release
