### ISSUE TITLE
Build a 32-bit app

### ISSUE THREAD

**Issue by angle943** [thenewboston-developers/Account-Manager#366]
currently our Account Manager is in 64-bit, but we need also a 32-bit version

**Comment by leelatanniru** [comment]
@angle943 Can we have two scripts separately for 32 and 64 in package.json like..
"scripts": {
    "build-32bit": "yarn package && electron-builder --ia32",
    "build-64bit": "yarn package && electron-builder --x64",

I tried doing this in a single command like "build": "yarn package && electron-builder --ia32 --x64",
But i observed the zip file is getting overwritten. Screen shot attached below.
![Capture](https://user-images.githubusercontent.com/22635016/95000129-c79f1380-05db-11eb-8894-c1e80d55c32a.PNG)

**Comment by tpikachu** [comment]
![Screen Shot 2020-10-04 at 8 22 29 AM](https://user-images.githubusercontent.com/46133358/95020717-98ab9080-0621-11eb-9ebb-8bd909099a77.png)
