### ISSUE TITLE
Add copy button for My Signing Key

### ISSUE THREAD

**Issue by leelatanniru** [thenewboston-developers/Account-Manager#369]
**Bug Description**

**Steps to Reproduce**
1. Go to My Account 
2. For My Signing Key , there is no copy button.

**Expected behavior**
It would be easy for the user to have a copy button for signing key.

**Actual behavior**
No copy button for signing key. User need to manually select the text to copy the key.

**Account Number**
7972e740622fe935bd7ce8b1ad3f0a0034888adbebf6bcc9e60d9d640cfc84db

**Comment by leelatanniru** [comment]
I would like to work on this issue if the bug is approved and I get the updated UX wireframes. Thank you.

**Comment by kristykjlee** [comment]
This ticket is ready to go

**Add:** 
- [ ] Add 'Visibility' icon to the left of the 'Content_Copy' icon for the Signing Key block. 

**Style Update:** 
- [ ] Only use 'Content_Copy' icon and remove 'Copy' text for signing key block, and all account number blocks for all users that have this block. (your accounts, friends, banks) 

**Your Accounts**
- https://www.figma.com/file/M4wHv7B4JNig3bH2cywI9u/My-Accounts?node-id=362%3A513

**Friends**
- https://www.figma.com/file/M4wHv7B4JNig3bH2cywI9u/My-Accounts?node-id=318%3A15851

**Banks**
- https://www.figma.com/file/ObSUx1rum1MIeZkFT3XIn1/Bank-User?node-id=837%3A4160

**Comment by leelatanniru** [comment]
I would like to work on this. Thank you @kristykjlee

**Comment by leelatanniru** [comment]
I have added the copy button for signing key, removed the "copy" text in accounts and friends page. Haven't updated in the banks page as there is another task to update the UI in progress. 
https://github.com/thenewboston-developers/Account-Manager/issues/354

**Comment by webdeveloperswj** [comment]
@leelatanniru 
1. Add 'Visibility' icon to the left of the 'Content_Copy' icon for the Signing Key block in Your Accounts. [DONE] 
![image](https://user-images.githubusercontent.com/59204822/95053899-ae4ab400-070e-11eb-9267-ddab0b264bfb.png)

2.Only use 'Content_Copy' icon and remove 'Copy' text for signing key block, and all account number blocks for all users that have this block. (your accounts, friends, banks) [DONE]
![image](https://user-images.githubusercontent.com/59204822/95054029-da663500-070e-11eb-94b8-8882249dd626.png)
![image](https://user-images.githubusercontent.com/59204822/95054048-e3570680-070e-11eb-9152-5e4638a361e2.png)

**Comment by angle943** [comment]
@leelatanniru this ticket has been completed, right? Do you know which PR it was associated with?

**Comment by leelatanniru** [comment]
@angle943 here it is https://github.com/thenewboston-developers/Account-Manager/pull/374
