### ISSUE TITLE
Update Account Manager Desktop Icon

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Account-Manager#372]
![tnb logo](https://user-images.githubusercontent.com/8547538/95008067-33c54b80-05cb-11eb-8a01-54d7b101163d.png)

**Comment by tpikachu** [comment]
![image](https://user-images.githubusercontent.com/46133358/95020932-24321b00-063c-11eb-91d7-99f1cffcc9cc.png)

**Comment by tpikachu** [comment]
![image](https://user-images.githubusercontent.com/46133358/95020983-4a57bb00-063c-11eb-81fb-4f7e888bc46e.png)
