### ISSUE TITLE
After sending points, balance is not updated immediately.

### ISSUE THREAD

**Issue by leelatanniru** [thenewboston-developers/Account-Manager#375]
**Bug Description**
After sending points, balance is not updated immediately. It is getting updated when user visits another page.

**Steps to Reproduce**
1. Click on send points.
2. Choose friend's account number and enter points.
3. Click on send. Observe that notification appeared after sending points successfully.
4. Observe that the balance on the top left corner is not updated.
5. When user visits another page, the balance is getting updated.

**Expected behavior**
Balance should be updated immediately after sending points.
**Actual behavior**
Balance is not getting updated immediately.

**Screenshots/Recordings**
Please find the attached screen recording.

[recording.zip](https://github.com/thenewboston-developers/Account-Manager/files/5323337/recording.zip)

**OS and Browser**
 - OS: Windows 10
 - Browser: Chrome

**Account Number**

7972e740622fe935bd7ce8b1ad3f0a0034888adbebf6bcc9e60d9d640cfc84db

Your account number where the reward points for this bug bounty will be sent (pending review and approval).

**Comment by lapstjup** [comment]
@leelatanniru and @buckyroberts Can I give this a shot if no one else has already picked it up ?

**Comment by leelatanniru** [comment]
@lapstjup ok from my end.

**Comment by lapstjup** [comment]
@buckyroberts I have added a possible fix but there is more to it. Resolved in #414.

**Comment by angle943** [comment]
@leelatanniru and @lapstjup I can't replicate this behavior at all. Do you think it was a network issue on your ends? Can you guys try to replicate this?

**Comment by lapstjup** [comment]
@angle943 
I actually thought this behaviour will happen since in processUpdatedBalances was only being called when recipient is a managedAccount. But in case it's a managedFriend, amount will also get debited from the managedAccount and that was not covered. So that's what i did in #414 

Let me know if I am missing something here.

Attaching the video link for your reference.
https://drive.google.com/file/d/1NzuoMHMlyxwPyoZINmONEPY1fDXPmU3e/view?usp=sharing

**Comment by leelatanniru** [comment]
@angle943  I am able to replicate this behavior at my end. The balance at the top left corner is not getting updated immediately after I sent points to a friend. I have attached video for reference.

**Comment by shahraizali** [comment]
Hi @leelatanniru! The recording you provided is either corrupt of maybe some codec issue on my end but its not working for me. However @angle943 I was able to replicate the issue as well I noticed 2 separate issues. 
1. The amount account balance in side panel is not updating even after hitting that refresh icon at the top.
2. The main issue that is reported here i.e. account balance in side panel not updating after transaction right away. 
NOTE: The friends balance is updated when I click on any other friend If I have multiple but still my balance is not updated unless I click on my account and then it updated the amount in side panel.

Here is the video recording: https://share.vidyard.com/watch/qDpSHYSojekx5Q8h8vf38w?

I am testing the latest upstream master branch.

**Comment by shahraizali** [comment]
Point 1 mentioned only happens if you have opened a friend's account and then you are refreshing.

**Comment by leelatanniru** [comment]
@angle943  are you able to reproduce the issue at your end?

**Comment by angle943** [comment]
ah nope @leelatanniru :( . We'll keep this issue open for now

**Comment by angle943** [comment]
should be fixed with recent updates
