### ISSUE TITLE
When Signing  Key is not visible then it should display "Visibility_Off" icon and vise versa

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#380]
**Bug Description**
When Signing  Key is not visible then it should display "Visibility_Off" icon and vise versa

**Steps to Reproduce**
1. Go to 'My Accounts"
2. Check in Signing key for Eye icon

**Expected behavior**
When Signing key is not visible it should display  "Visibility_Off" icon and vise versa

**Actual behavior**
When Signing  Key is not visible then also it displays "Visibility_On" icon and vise versa

**Screenshots/Recordings**
When key not visible "Visibility_On" icon displayed
![image](https://user-images.githubusercontent.com/59204822/95060296-b5c28b00-0717-11eb-8974-0cb91416da64.png)

When key visible "Visibility_Off" icon displayed
![image](https://user-images.githubusercontent.com/59204822/95060571-1651c800-0718-11eb-9336-2f572a05858b.png)

**OS and Browser**
 - OS: [Windows 7]

**Additional context**
App version 1.0.0-alpha.21

**Account Number**
15e164325715c9552911caf7e3ea1759f4c2ccba5fd82864a4d811d67935c4f9

**Comment by leelatanniru** [comment]
According to the wireframe it was different. @kristykjlee could you please confirm. If this is valid issue..I would like to work on it. Thanks:))

**Comment by kristykjlee** [comment]
> According to the wireframe it was different. @kristykjlee could you please confirm. If this is valid issue..I would like to work on it. Thanks:))

@leelatanniru The mocks are the correct version. For hidden keys/password, the correct pattern is to show the eyeball (visibility icon) and when you hover over this, it will pull up a tooltip that says 'Show'. Similar to how hidden password interactions works, thats standard. No need to work on this ticket.

**Comment by leelatanniru** [comment]
Thanks for the confirmation @kristykjlee
