### ISSUE TITLE
Crawl and Clean for Validators

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Account-Manager#382]
**OVERVIEW**
- Similar to the /crawl endpoint that allows users to discover and create new peers, we also need a /clean endpoint that removes all non-responsive/offline peers from the database. This is because for our p2p network architecture, new peers are always going to be coming online and going offline. This will allow the servers to save resources by removing any offline nodes and prevent future communication attempts with those offline nodes.

**ACCEPTANCE CRITERIA**
- [ ] Add Clean Status under Crawl Status for authenticated Banks & Validators.
- [ ] Clean Status will have 2 states, 1) Cleaning, 2) Not Cleaning
- [ ] If Clean Status is Cleaning (Sail Green 500), include a Stop button next to it
- [ ] If Clean Status is Not Cleaning (Sail Red 500), include a Clean button next to it

https://www.figma.com/file/ObSUx1rum1MIeZkFT3XIn1/Bank-User?node-id=837%3A840

<img width="1431" alt="Screen Shot 2020-10-12 at 7 06 59 PM" src="https://user-images.githubusercontent.com/8547538/95807087-293b3e00-0cbe-11eb-92e2-d9492a43c29b.png">

## Update
This logic is already implemented for the Banks. It just needs to be implemented for the Validators (excluding the PV).

<img width="1264" alt="Screen Shot 2021-01-14 at 8 02 59 PM" src="https://user-images.githubusercontent.com/8547538/104680025-c930ab00-56a3-11eb-9ce9-25adedc41f85.png">

<img width="1055" alt="Screen Shot 2021-01-14 at 8 03 08 PM" src="https://user-images.githubusercontent.com/8547538/104680029-cafa6e80-56a3-11eb-9f4c-ff642e3a548c.png">

**Comment by buckyroberts** [comment]
Updated to draft, waiting for BE changes.
