### ISSUE TITLE
Style Validator Overview Page like Banks Overview Page

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Account-Manager#388]
Recently the Banks Overview page was redesigns to use "panels" rather than having just one big table.

<img width="1041" alt="Screen Shot 2020-10-06 at 8 49 43 PM" src="https://user-images.githubusercontent.com/8547538/95285403-93169c00-0815-11eb-9bca-ce27eb693e95.png">

Now we would like to style the Validator Overview page the same way. 

**The 2 left panels will be:**
- Tx Fee (per Tx)
- _all other information_

**The 1 right panel will be:**
- Validator Network ID / Validator Account Number (same exact logic as Bank)

<img width="829" alt="Screen Shot 2020-10-06 at 8 49 52 PM" src="https://user-images.githubusercontent.com/8547538/95285411-9578f600-0815-11eb-9e5a-d7352462a53d.png">

**Comment by webdeveloperswj** [comment]
@buckyroberts Looking good
![image](https://user-images.githubusercontent.com/59204822/95326657-8bf89800-08c0-11eb-9233-380ca7ef99b7.png)
