### ISSUE TITLE
No option available to Remove signing keys for bank

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#393]
**Bug Description**
No option available to Remove signing keys for bank

**Steps to Reproduce**
1. Go to 'Banks' page
2. Click on three dots on top right corner 
3. Check options

**Expected behavior**
Option should be available to remove signing keys for banks 

**Actual behavior**
No option available to Remove signing keys for bank

**Screenshots/Recordings**
![image](https://user-images.githubusercontent.com/59204822/95448510-130d4500-0981-11eb-83a9-d0399670e2fe.png)

**OS and Browser**
 - OS: [e.g. Windows 7]

**Additional context**
App version : 1.0.0-alpha.22

**Account Number**
 15e164325715c9552911caf7e3ea1759f4c2ccba5fd82864a4d811d67935c4f9

**Comment by kristykjlee** [comment]
This has been moved to the Design Repository
