### ISSUE TITLE
Error message can be improved when user enters invalid IP Address for bank account

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#395]
**Bug Description**
Error message can be improved when user enters invalid IP Address for bank account

**Steps to Reproduce**
1. Go to 'Bank'
2. Go to Add bank
3. Add invalid bank address
4. See error message 

**Expected behavior**
When user try connect  to invalid bank IP address then error message should be "Bank do not exists"or "Invalid bank address"

**Actual behavior**
It displays "Timeout exceeded error"

**Screenshots/Recordings**
![image](https://user-images.githubusercontent.com/59204822/95457056-f1668a80-098d-11eb-8cea-5041981229ea.png)

**OS and Browser**
 - OS: [Windows 7, Linux]

**Additional context**
App version : 1.0.0-alpha.22

**Account Number**
 15e164325715c9552911caf7e3ea1759f4c2ccba5fd82864a4d811d67935c4f9

**Comment by brian316** [comment]
Created a pull request for this issue [here](https://github.com/thenewboston-developers/Account-Manager/pull/405)
