### ISSUE TITLE
Move "Daily Rate" to separate panel

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Account-Manager#399]
On the Validator Overview page, move "Daily Rate" to a separate panel.

https://www.figma.com/file/nUhBBfzmAynizCEymRR01G/Validators?node-id=234%3A2110

<img width="1429" alt="Screen Shot 2020-10-12 at 7 40 24 PM" src="https://user-images.githubusercontent.com/8547538/95809106-d44df680-0cc2-11eb-844b-30487bc7c80d.png">

**Comment by leelatanniru** [comment]
@angle943 @buckyroberts  I just made a PR for this issue. https://github.com/thenewboston-developers/Account-Manager/pull/401
