### ISSUE TITLE
Error installing the Account-Manager

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Account-Manager#40]
![image](https://user-images.githubusercontent.com/8547538/87462420-c229c280-c5c4-11ea-9832-c7b105e72522.png)

**Comment by Hristijan95** [comment]
This PR on [electron-devtools-installer](https://github.com/MarshallOfSound/electron-devtools-installer/pull/140) should fix the issue. 

Since this error is not fatal, maybe we just wait for a new release of electron-devtools-installer?

**Comment by angle943** [comment]
good find. we've updated `electron-devtools-installer`, that should've fixed the issue
