### ISSUE TITLE
While Editing nickname duplicate name should not be accepted

### ISSUE THREAD

**Issue by angle943** [thenewboston-developers/Account-Manager#400]
**Bug Description**
While Editing nickname already existing name is also accepted

**Steps to Reproduce**
1. Go to Validators
2. Click on three dots at top right corner
3. Edit nickname
4. Add already existing nickname

**Expected behavior**
While Editing nickname duplicate name should not be accepted 

**Actual behavior**
While Editing nickname already existing name is also accepted

**Screenshots/Recordings**
https://recordit.co/eOQt1G5Llh

**OS and Browser**
 - OS: [Windows 7]

**Additional context**
App version 1.0.0-alpha.21

**Account Number**
15e164325715c9552911caf7e3ea1759f4c2ccba5fd82864a4d811d67935c4f9

Originally created as an issue in the Validator repo: https://github.com/thenewboston-developers/Validator/issues/62

**Comment by shahraizali** [comment]
@angle943 Hi! PR is already up for this and is assigned to you. Kindly review and let me know if any changes required
Thanks

**Comment by shahraizali** [comment]
@buckyroberts Its merged can you please assign this to me I wantem points 🤑💰
