### ISSUE TITLE
Add option to check app version in app in footer so that user come to know app version

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#404]
Add option to check app version in app in footer so that user come to know app version
![image](https://user-images.githubusercontent.com/59204822/96084717-2bc7ae80-0edd-11eb-9d37-5523ca7c34bc.png)

**Comment by buckyroberts** [comment]
@webdeveloperswj @kristykjlee @angle943 If we know the version of the app, then we can have an endpoint that just checks for the latest version (using the GitHub API). If they are different then we can display some UI element saying "New version available" or "Update available" or something.

**Comment by angle943** [comment]
![screen_shot_2020-10-19_at_8 33 37_pm](https://user-images.githubusercontent.com/5943963/96537191-826d1980-124a-11eb-950c-59465a06522e.png)

To show version #, something like this might be sufficient

**Comment by kristykjlee** [comment]
This has been moved to the Design Repository
