### ISSUE TITLE
Add the functionality to use font-weight with our Inter Font

### ISSUE THREAD

**Issue by angle943** [thenewboston-developers/Account-Manager#416]
Currently, we can't set the font-weight with our Inter fonts. We have to change the font-family to make it bold. For example: font-family: var(--font-family-inter-bold).

Research into how to update this. We don't want to update the font weight by changing the font-family.

Please look at https://github.com/thenewboston-developers/Website/issues/293 and it's associated PR for inspiration

**Comment by colfax23** [comment]
I'll take this one
