### ISSUE TITLE
Add "Download CSV" option for transaction history

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#418]
![image](https://user-images.githubusercontent.com/59204822/97167573-0ecc8e80-17ad-11eb-88b0-ba9305ce638d.png)

**Comment by mofodox** [comment]
@kristykjlee Do we need this feature now?

**Comment by kristykjlee** [comment]
This has been moved to the Design Repository

**Comment by denistsoi** [comment]
I'd like to work on this so i can export my transactions for tracking transaction history - thanks
