### ISSUE TITLE
Edit Nickname Not Working Properly In Friend Account

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#420]
**Bug Description**
I have renamed my account name in windows operating system and see it that effects on linux operating system my friends account section i could'nt see that effect when i refresh it

**Steps to Reproduce**
1. launch thenewboston (version 1.0.0-alpha.26) in windows
2. Click on My Accounts + 
3. Create New Account
4. go to linux and launch the thenewboston 
5. click on My Friends +
6. Enter nickname & friends Account number
7. click on add button
8. go to the windows and  Rename My accounts 
9. select your account e.g.(test2)
10. click on top right side corner three dots
11. click on Edit nickname 
12. edit the name & save 
13. go to linux and thenewboston app
14. check my friends changed friend name effect not sea it still previous name shows

**Expected behavior**
the user has changed there name / edited that effects displayed in other operating system like linux my friends section

**Actual behavior**
The linux operating system in thenewboston application renamed my friends not working

**Screenshots/Recordings**
https://prnt.sc/vcduct

**OS and Browser**
 - OS:  Windows 10
 -OS: LINUX          

 - Browser [ Chrome]

**Comment by buckyroberts** [comment]
Nicknames are not shared across the network, only used for local organization purposes.
