### ISSUE TITLE
upgrade react-scripts

### ISSUE THREAD

**Issue by angle943** [thenewboston-developers/Account-Manager#423]
upgrade react-scripts to v4.

Make sure you run `npm run lint` and make sure there are no errors

**Comment by amarjeet987** [comment]
on it.

**Comment by amarjeet987** [comment]
PR : https://github.com/thenewboston-developers/Account-Manager/pull/427

**Comment by rust-7** [comment]
Is anyone working on it ? If yes maybe someone needs help ?
