### ISSUE TITLE
[linux] Received Points from Friends That transaction Entry not shows in Transaction

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#425]
**Bug Description**
When Sending Points From One Account To friend Account That Transaction Entry Not Shows In Friend Transaction side Only Notified Him

**Steps to Reproduce**
1. Click On Send Points Button
2. Select Friends Account
3. Enter Points & Click on Send Button
4. Go To The Friends Account 
5.click on Transaction Tab

**Expected behavior**
Received Points from Friends That Entry Shows in Friends Transaction Tab

**Actual behavior**
Received Points from Friends That Entry Not Shows in Friends Transaction Tab

**Screenshots/Recordings**
https://prnt.sc/vdqmzu
	

**OS and Browser**
 - OS: Linux & Windows
 - Browser [ Chrome]

**Comment by nishp77** [comment]
pls assign this to me

**Comment by abdulabdullahi** [comment]
We do hope we contribute our quarter

**Comment by vildantursic** [comment]
Hi,
Is there a way to setup dummy / additional account locally for reproducing this issue on dev environment?
