### ISSUE TITLE
TNB Account Manager (Windows) - Refresh Button

### ISSUE THREAD

**Issue by dwkim922** [thenewboston-developers/Account-Manager#430]
**Bug Description**
- Double clicking the refresh button on TNB Account Manager, highlights "**Change** Active Bank"
- Triple clicking the refresh button on TNB Account Manager, highlights "**Change Active Bank**"

**Steps to Reproduce**

1. Run TNB Account Manager on Windows
2. Double Click the refresh icon on the top left ("<u>Change </u>Active Bank" will be highlighted)
3. Triple Click the refresh icon on the top left ("<u>Change Active Bank</u>" will be highlighted)

**Expected behavior**
- Whether I click it once or twice or even a billion times, for "Change Active Bank" not to be highlighted.

**Actual behavior**
- Double clicking the refresh button on TNB Account Manager, highlights "**Change** Active Bank"
- Triple clicking the refresh button on TNB Account Manager, highlights "**Change Active Bank**"

**Screenshots/Recordings**
![image](https://user-images.githubusercontent.com/71767816/98331802-b2852c80-2040-11eb-84a8-dddb0ac05848.png)
![image](https://user-images.githubusercontent.com/71767816/98331881-dcd6ea00-2040-11eb-827b-0a848b2ef3b3.png)

**OS and Browser**
 - OS: Windows 10 Pro v1909

**Additional context**
This isnt really a big issue, but it just bothers me, and i dont think its supposed to do that.

**Account Number**
5020d46aaf94dd966a2e88b96ba7c143e3c778425b4329e49bac3d9c46829253

**Comment by btk** [comment]
I don't think this is a use case, since we don't expect user to double click the buttons, but #433 fixes it
