### ISSUE TITLE
TNB Account Manager (Mac) - Apple cannot check it for malicious software

### ISSUE THREAD

**Issue by 3mrdev** [thenewboston-developers/Account-Manager#431]
**Bug Description**
“TNB Account Manager” can’t be opened because Apple cannot check it for malicious software.

**Steps to Reproduce**
1. Install the dmg from thenewboston website
2. Open the app
4. See permission error

**Expected behavior**
Open the app 

**Actual behavior**
Apple doesn't want to open the app because it cannot check it for malicious software 

**Screenshots/Recordings**
![Screen Shot 2020-11-06 at 4 02 16 PM](https://user-images.githubusercontent.com/17106146/98375097-532c1a00-204a-11eb-8725-3a20bee3008a.png)

**OS and Browser**
 - OS: macOS Catalina 10.15.3
 - Browser: Chrome

**Additional context**
Laptop Specs

MacBook Pro (13-inch, Mid 2012)
2.5 GHz Dual-Core Intel Core i5
8 GB 1600 MHz DDR3
Intel HD Graphics 4000 1536 MB

**Account Number**
e483f8366c1c760ba384225bc19e44c63e012f8149a181a9a0f3e34ac5c336e3

**Comment by dgilmore33** [comment]
I'm on a MacBook Air 13-inch 2017, Catalina 10.15.7, and I was able to download it

**Comment by Hristijan95** [comment]
As far as I know this is a normal behavior, apple checks for all apps that are not downloaded from the AppStore and warn users that they could harm them. To open the app you should just click "Show in Finder" and you will be taken to the application icon where you can click Right Click -> Open and you will be presented with a new choice where you can select Cancel / Open. When you click open, you'll never see this message again.

I am not sure if anything can be done from our side to avoid the issue.

**Comment by Hristijan95** [comment]
Actually, I was wrong, there is a way to fix this. I did a little bit of research and I found [this medium article](https://medium.com/@TwitterArchiveEraser/notarize-electron-apps-7a5f988406db) which explains what's happening and a way to fix it. 
I don't have the time to dig deeper into the issue at the moment, but if no one picks it up, I will come back to it when I can.

**Comment by nishp77** [comment]
@3mrdev i have updated the electron-builder.json so that it could work pls use this attached file. Pls try this as i don't have a mac to generate the release but just add this few lines in it. Hope it works!!

![image](https://user-images.githubusercontent.com/35785259/98493987-6fbe8280-2201-11eb-8a48-b278f573c426.png)

**Comment by 3mrdev** [comment]
> As far as I know this is a normal behavior, apple checks for all apps that are not downloaded from the AppStore and warn users that they could harm them. To open the app you should just click "Show in Finder" and you will be taken to the application icon where you can click Right Click -> Open and you will be presented with a new choice where you can select Cancel / Open. When you click open, you'll never see this message again.
> 
> I am not sure if anything can be done from our side to avoid the issue.

Yes ... You can't open it this way

![Screen Shot 2020-11-09 at 5 58 46 PM](https://user-images.githubusercontent.com/17106146/98564716-5d9e1c00-22b5-11eb-8f23-fe0fece66132.png)

**Comment by 3mrdev** [comment]
> @3mrdev i have updated the electron-builder.json so that it could work pls use this pic. Pls try this as i don't have a mac to generate the release but just add this few lines in it. Hope it works!!
> 

Actually i am not an electron developer but i will try it if i had the time .. Maybe someone else will come and try your json file

**Comment by belamar1** [comment]
I confronted the same problem clicked Ok, then control+mouse click, and select open, and voila! it is working

**Comment by DOHtero** [comment]
If you forget which button to hold onto while trying to open it, a user can also secondary click TNB Account Manager -> click "Open" and the option to open the application will work as well. This is just MacOS security feature called Gatekeeper hard at work.

Recorded a screencap of regular double-clicking vs secondary clicking
![tnb](https://user-images.githubusercontent.com/335606/98901604-0f8a4380-2482-11eb-8105-6ba555a8dc4e.gif)

**Comment by DOHtero** [comment]
So in order for this app to open up without it coming from the App Store and without needing to do any special actions to open it (holding a key while clicking, secondary click, etc) you would need to get the App "Notarized" through their developer process. After reading a few articles, it seems like it is an automated process mostly but I am guessing this would required a developer's license to do it.

Here is the Apple Developer's article I found on it that walks you through how to setup the App in xcode for being notarized before distribution.
https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution

Hope it helps! ;)

**Comment by barajas123** [comment]
yes this is normal Mac behavior, its always happens with apps not downloaded from the App Store. Try again and open the TNB Account Manager APP, it will not open > go to system preferences > Security & Privacy , and there will be a message asking if you want to open anyway.
![Screen Shot 2020-11-12 at 9 21 24 AM](https://user-images.githubusercontent.com/46165581/98951588-703c6f00-24c8-11eb-94ac-00c5bd3ef343.png)

**Comment by Hristijan95** [comment]
@DOHtero , yes, I think you are correct. We'll try to look into it as soon as possible.

**Comment by nifex007** [comment]
> I confronted the same problem clicked Ok, then control+mouse click, and select open, and voila! it is working

you are a prophet. thanks 👍

**Comment by angle943** [comment]
reopening this issue, as it has not been fixed
