### ISSUE TITLE
[Notification Modal Header] Padding on the left is too much

### ISSUE THREAD

**Issue by mofodox** [thenewboston-developers/Account-Manager#439]
**Bug Description**
More on the UI for the notification modal is active. The notification header's padding left is too much at 32px and the other paddings (Top, right, bottom) are not consistent.

**Steps to Reproduce**
1. Click on 'Notification Icon'
2. See UI error

**Expected behavior**
It should have a 16px for the padding (top, right, bottom, left).

**Actual behavior**
The padding is consistent.

**Screenshots/Recordings**
https://share.getcloudapp.com/E0urQlXp

**OS and Browser**
 - macOS Catalina 10.15.7

**Account Number**
ddef8a7ea0d98f8605703102f5b25e587d612ba7917afc1c9eb0ee904ae181c0

**Comment by whitelionx** [comment]
Resolved it at #441

**Comment by itsnikhil** [comment]
I request maintainers to add coins in the label as a reward for this fix
