### ISSUE TITLE
[Windows]There Is No Option To Set As a Validator or Changed Validator 1.0.0-alpha.28 

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#449]
**Bug Description**
can't be able to set as different validator or changed validator option not available

**Steps to Reproduce**
1. launch TNB V 28
2. Add 2 Validators
3. Select Validator
4. Click on Top right side corner 3 dots

**Expected behavior**
In top right corner three dots there option should be available set as validator or changed validator 

**Actual behavior**
There is no option available for changed validator or set as validator in top right side corner three dots

**Screenshots/Recordings**
https://prnt.sc/vfw4sf

**OS and Browser**
 - OS:  Windows 10]
 - Browser [ Chrome]

**Comment by lapstjup** [comment]
@buckyroberts Not sure if a user can set a Primary Validator. Isn't that the responsibility of the trusted Bank ?
The [docs](https://www.thenewboston.com/guide/banks) say that User can set Banks but only Banks can choose their primary validators.

**Comment by buckyroberts** [comment]
@lapstjup Correct, users only choose their Banks, not the validators. I will close this issue.
