### ISSUE TITLE
[Linux]TNB v28 Web Application can't display on linux operating system.

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#453]
**Bug Description**
TNB v28 Web Application Display icon not shown it

**Steps to Reproduce**
1.Go to "https://thenewboston.com/"
2.Download For Linux TNB V28
3.Installed Application On TNB V28
4.See the web icon TNB v28

**Expected behavior**
Every Operating System App Icon Shown It

**Actual behavior**
Linux Operating System App Icon Not show it

**Screenshots/Recordings**
https://imgur.com/isWcuhp.png

**OS and Browser**
 - OS: [e.g. Linux]

**Comment by matheusfillipe** [comment]
Can you still confirm it in alpha 29? Are you sure something isn't missconfigured on your file explorer? 

Linux has many file explorers that can work differently. Here on dolphin and nautilus I see it for both versions:

**dolphin**
![image](https://user-images.githubusercontent.com/24435787/99747488-5ea32a80-2ab9-11eb-9fc2-6fd174addd18.png)

**nautilus**
![image](https://user-images.githubusercontent.com/24435787/99747581-8d210580-2ab9-11eb-9a8a-6067403af10d.png)

**thunar**
![image](https://user-images.githubusercontent.com/24435787/99747676-c9546600-2ab9-11eb-9110-328e7f5cf37e.png)

But doesn't work on a fresh installed pcmanfm:

**PCManFM**
![image](https://user-images.githubusercontent.com/24435787/99748017-6ca57b00-2aba-11eb-8679-79aa06855683.png)

So this really depends on system configuration and is not a problem on how they are building the app. This issue should be closed.


**My system info**

OS: Arch Linux x86_64, DE: KDE Plasma 5.20.2, CPU: Intel i7-7700HQ (8) @ 3.800GHz, GPU: NVIDIA GeForce GTX 1050 Ti Mobile, GPU: Intel HD Graphics 630, Memory: 15.5 GiB

**Comment by matheusfillipe** [comment]
@webdeveloperswj Can you confirm that you don't see the icon for any other appimage application on pcmanFM?

72d31b3aa84e4a0cf58dc5527b5a0a54a4499716994a2f7c0507e32b9985156c

**Comment by angle943** [comment]
closing for now
