### ISSUE TITLE
[Linux]TNB v28 Web Application Set as validator or change Validator option not available 

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#454]
**Bug Description**
when changing the validator its not option available for set as new validator or changed validator 

**Steps to Reproduce**
1. Launch TNB version 28 
2. Click on Validator's "+"
3. Enter Valid IP Address
4. Click On Add button
5.Select another validator 
6.click on top right side corner three dots

**Expected behavior**
changed validator option should be available.

**Actual behavior**
changed validator option not available.

**Screenshots/Recordings**
https://imgur.com/Unxz3f3.png

**OS and Browser**
 - OS: [linux]

**Comment by buckyroberts** [comment]
Users do not choose their primary validator, your active bank chooses that for you.
