### ISSUE TITLE
[Linux]Sending Coins from linux account to windows Account friends Transaction history record not showed 

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#455]
**Bug Description**
When Sending Points From One Account To friend Account That Transaction Entry Not Shows In Friend Transaction side Only Notified Him

**Steps to Reproduce**
1.Click On Send Points Button
2.Select Friends Account
3.Enter Points & Click on Send Button
4.Go To The Friends Account
5.click on Transaction Tab

**Expected behavior**
Transaction entry not shown it

**Actual behavior**
Transaction entry shown it 

**Screenshots/Recordings**
https://prnt.sc/vginl0

**OS and Browser**
 - OS: [Linux]

**Comment by nishp77** [comment]
Duplicate issues as its already there:- #425

**Comment by webdeveloperswj** [comment]
> Duplicate issues as its already there:- #425

Yes its a duplicate issue that issue appears on TNB Ver 26 and now TNB Ver 28 still same issue that's reason posted again..
