### ISSUE TITLE
We can not Login

### ISSUE THREAD

**Issue by Ramin-RX7** [thenewboston-developers/Account-Manager#456]
Well we live in very very limited country because our government has problems with USA government. Due to this we are not able to have access from our country's ip to some websites and servers (so I usually use VPN) but for the first time I launched thenewboston without VPN and I faced this image
![Screenshot (172)](https://user-images.githubusercontent.com/52785580/98729604-69223d80-23b0-11eb-94cb-3f724e50d503.png)
and as all we know Bucky is not from those guys who don't care about these things and its important that everyone can be in thenewboston easily so I want to know is there any way to change servers or anything which can let us use the app without using IP changer apps

**Comment by harshit-singh99** [comment]
@buckyroberts  Can we have a list of banks hardcoded in the manager and have it try to others if connection to the first fails? That list can be updated by checking banks associated with the primary validator.
Currently the only other bank with non zero number of confirmation validators is 167.172.181.31 (it is in Germany, not the USA, so you can try connecting to it with http protocol on port 80).

**Comment by buckyroberts** [comment]
@Ramin-RX7 bumped up timeout to 10 seconds, can you see if that helps?

https://github.com/thenewboston-developers/Account-Manager/commit/d2cb4050f199b9d4a084375f8567f75f6081fc43
