### ISSUE TITLE
SendCoinsModal accepts negative integers

### ISSUE THREAD

**Issue by whitelionx** [thenewboston-developers/Account-Manager#460]
**Bug Description**
When I enter a negative value in the coins input I don't get any error message in the modal.

**Steps to Reproduce**
1. Go to the Account Manager.
2. Click on Send Coins.
3. On the Coins input enter a negative integer.
4. Error message doesn't show up

**Expected behavior**
Get a red error message like in other cases when wrong values are entered in the fields.

**Actual behavior**
No error message is being displayed.

**Screenshots/Recordings**
![image](https://user-images.githubusercontent.com/31674307/98802111-1168ee00-2413-11eb-99dc-c7187d730584.png)

**OS**
 - OS: [e.g. Mac OS]

**Account Number**
fb84a32a698a03dd327c4ce673f19fa0acf6e68cb50f143d5d7c080471bc4625

[How to Create an Account](https://thenewboston.com/account-manager/create-an-account)

**Comment by singh-sarabjeet** [comment]
It looks like it can be mac specific since it's working fine on windows.
![image](https://user-images.githubusercontent.com/11057104/98805755-12634500-243e-11eb-9362-d5b14aeea07e.png)

@whitelionx can you confirm that the error message doesn't come up when the coins box goes out of focus?

**Comment by whitelionx** [comment]
@singh-sarabjeet Yh, you are right sorry, was working on code and by chance edited the validations, sorry. Will close the issue. Thanks for reminding me.
