### ISSUE TITLE
[Windows]TNB ver_28 Refresh button  Function not working properly 

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#461]
**Bug Description**
I have deleted/removed  my friends account but still he is showing to me when i refreshing the TNB 28 app 

**Steps to Reproduce**
1. launch TNB ver28 
2. Click on my friends account (+)
3.Enter Nickname & Account number
4. Now Select that friend account 
5.Click on top right side corner three dots
6.Select removed friend option
7.Click on yes button 
8.click on refresh button

**Expected behavior**
Deleted Friend Account removed immediately with all data like Account balance, account number this info.

**Actual behavior**
When removed friend ,friend removed successfully but there data shows it like account balance,account number 

**Screenshots/Recordings**
https://prnt.sc/vha80x

**OS and Browser**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome]

**Comment by angle943** [comment]
this is intended behavior. its like being on a friend's facebook page, and then unfriending. You will still see their page, but now they won't be your friend anymore
