### ISSUE TITLE
[mac]Notification Function not working properly

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#463]
**Bug Description**
Notification not working properly

**Steps to Reproduce**
1. Installed TNB version 28 app on windows and mac o.s.
2. launch application on windows
3. Click on send coins button 
4. Select friend account(mac)
5.Enter Coins & click on send button

**Expected behavior**
Notified friend when receiving coins from friends account

**Actual behavior**
Not notified friend when receiving coins from friends account

**Screenshots/Recordings**
mac o.s.:- https://prnt.sc/vhaw93
windows o.s. https://prnt.sc/vhavk0

**OS and Browser**
 - OS: [e.g. Windows 10,mac]
 - Browser [e.g. Chrome]

**Comment by buckyroberts** [comment]
Due to bank not having any active confirmation services
