### ISSUE TITLE
[Windows]Same Account but balance shown differ

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#467]
**Bug Description**
Different Balance shown

**Steps to Reproduce**
1. Installed TNB 28 on windows machine
2. launch TNB 28 app
3. create my account click on (+)
4. add that account as friend account

**Expected behavior**
Balance shown friend account same both side my account and friend account

**Actual behavior**
Balance shown differ

**Screenshots/Recordings**
https://prnt.sc/vhqxw9

**OS and Browser**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome]

**Comment by buckyroberts** [comment]
Signing key and account number are not the same.
