### ISSUE TITLE
[windows]Balance Not Update Immediately  

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#469]
**Bug Description**
When sending coins balance not reduced immediately

**Steps to Reproduce**
1. Installed TNB28
2. launch TNB28 app
3. click on send button
4.select account 
5.enter coins
6.click on send button

**Expected behavior**
when sending coins to someone balance update immediately

**Actual behavior**
balance not update immediately you have to click on refresh button then balance update

**Screenshots/Recordings**
https://prnt.sc/vhr8o9

**OS and Browser**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome]

**Comment by webdeveloperswj** [comment]
> duplicate of #375 ?

yes its duplicate issue but this issue not solve in TNB version 28 so that's reason reposted

**Comment by lapstjup** [comment]
@webdeveloperswj Can we close this one ? I know it's not resolved in latest release but #375 has a whole discussion about this. Probably should make this priority @charnysh-dev  - can you verify this when you have time ? - I also have a PR #414 for this which was closed but did fix the issue for me.
