### ISSUE TITLE
[Linux]TNB_VER_28 Account Number using as a Signing Key (Measure security issue)

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#470]
**Bug Description**
Account number using as a signing key.

**Steps to Reproduce**
1.Installed TNB Ver 28.
2.launch TNB App on Linux Machine.
3.Click on my account(+).
4.Select Create New Account.
5.Enter nickname & click on create button.
6.Copy that Account Number.
7.Click on my accounts(+).
8.Select Add Existing Account.
9.Enter nickname & paste account number as a signing key section.
10.click on add button.

**Expected behavior**
Doesn't Accept Account number As a signing key.

**Actual behavior**
Account number Accepted As a signing key.

**Screenshots/Recordings**
https://prnt.sc/vieb2p
https://prnt.sc/viebtu

**OS and Browser**
 - OS: [Linux]
 - Browser [Chrome]

**Comment by buckyroberts** [comment]
Closing, duplicate of - https://github.com/thenewboston-developers/Account-Manager/issues/500
