### ISSUE TITLE
[mac] Account creation with space instead of a nickname

### ISSUE THREAD

**Issue by dstekanov** [thenewboston-developers/Account-Manager#478]
**Bug Description**
It is possible to create an account using only space as a nickname and it's not displayed on the left side menu

**Steps to Reproduce**
1. Install the TNB v28
2. Launch the app
3. Click on "My Accounts" (+ sign) on the left side menu
4. Select "Create New Account" 
5. Enter one or few spaces
6. Click "Create" button

**Expected behavior**
Nickname must include at least 1 character or digit

**Actual behavior**
An account with a blank name is created, but it is not shown on the left side menu and does not display the account name

**Screenshots/Recordings**
https://prnt.sc/vkqm4n

**OS and Browser**
 - OS: macOS Catalina
 - Browser Chrome

**Account Number**
a9a4823b71318bf481cf58f97fd3e8090c7221a84ae8ad25d8deff8922acfa8a

**Comment by omar-aguilar** [comment]
Which characters are valid  for a nickname?
it may be simpler to just validate against those characters than for example check for whitespaces, which then it may be needed to deal with things like zero width space, for example:
```js
'a​a' === 'aa' // false
```
Maybe that is not even a thing to care about :man_shrugging:
