### ISSUE TITLE
Add Dropdown of Added Banks in "Change Active Bank" Dialog [Suggestion]

### ISSUE THREAD

**Issue by AbhayAysola** [thenewboston-developers/Account-Manager#481]
**Suggestion Description**
I have a few banks added, and they show up fine. When I want to change my active bank, I have to add the details like IP Address, Port, Protocol etc. What would be nice is, instead of having to type all of that out, I could select from the already added banks via a dropdown. 

**Steps to Reproduce**
1. Add one or two banks
2. Click "Change Active Bank"
3. See that no list of banks appears.

**Expected behavior**
A dropdown of previously added banks.

**Actual behavior**
Fields to enter details of bank manually

**Account Number**
8928526805de48e4bf2ed2a9b4b839e6b2603018ecdfbf4cffdb2065e01a3ed1

**Comment by buckyroberts** [comment]
@AbhayAysola after adding a bank to your Managed Banks

<img width="493" alt="Screen Shot 2020-11-19 at 1 53 34 PM" src="https://user-images.githubusercontent.com/8547538/99728710-ad77a280-2a6e-11eb-9ac6-14e3084544ed.png">

you will see an option to set that as your active bank.

<img width="651" alt="Screen Shot 2020-11-19 at 1 52 57 PM" src="https://user-images.githubusercontent.com/8547538/99728607-8b7e2000-2a6e-11eb-9fec-de9481a64ab8.png">

**Comment by AbhayAysola** [comment]
Whoops, my bad. This is also good :)
