### ISSUE TITLE
"Add" validator/bank button is active with empty required fields

### ISSUE THREAD

**Issue by dstekanov** [thenewboston-developers/Account-Manager#482]
**Bug Description**
`Add` button is active after opening "Add Bank"/"Add Validator" dialog.

**Steps to Reproduce**

1. Click the plus button to the right of "Banks" / "Validators" on the left side menu

**Expected behavior**
`Add` button must be inactive and not clickable

**Actual behavior**
`Add` button is active. After clicking it became inactive.

**Screenshots/Recordings**
https://prnt.sc/vm92gd

**OS and Browser**
- OS: macOS Catalina
- Browser Chrome

**Account Number**
a9a4823b71318bf481cf58f97fd3e8090c7221a84ae8ad25d8deff8922acfa8a

**Comment by Jared-Ivory** [comment]
I believe I have found the root of the issue. The form doesn't validate until the model is touched. For the initial render button, the disable logic results in the validation resulting as true. Applying the validateOnMount prop to the `<Formik validateOnMount/>` JSX object "fixes" the problem but results in a initial blink of the button changing to the disable state as the validate results in false.

**Comment by Jared-Ivory** [comment]
Actually I believe a better solution is to remove the ignoreDirty prop of the Validator and Bank Modal. The FormButton will initially rendered with a disabled state due to [!dirty](https://formik.org/docs/api/formik#dirty-boolean). The Formik Validator for the forms will still be able to run as you change the values within the form. I can see the need of ignoring this property in other applications, but in the case of these two Modals and their content it is best to not ignore the dirty state when determining the disabled state.

**Comment by Jared-Ivory** [comment]
Call me a novice or whatever but how do you make a pull request like this? I would have done this myself but I’ve never worked on a project with others before.

**Comment by jamessspanggg** [comment]
> Call me a novice or whatever but how do you make a pull request like this? I would have done this myself but I’ve never worked on a project with others before.

hi Jared you would first fork the project to your own github account here:
<img width="1246" alt="Screen Shot 2020-11-20 at 11 46 41 PM" src="https://user-images.githubusercontent.com/32864116/99819683-bc537780-2b8a-11eb-8259-6947a8e6135f.png">

After that proceed to clone the project in your account by executing `git clone [link]` in your terminal/shell. The link is available in the forked repository in your account:
<img width="1016" alt="Screen Shot 2020-11-20 at 11 49 35 PM" src="https://user-images.githubusercontent.com/32864116/99819960-1e13e180-2b8b-11eb-89aa-b456ae2881ea.png">

After cloning the project to your system, you can start developing your fix/feature in a separate branch using `git checkout -b`. After which you commit your changes and push the change back up to your account. From the newly created branch, you can create a PR to the team's repo.

The full demonstration: https://www.youtube.com/watch?v=OHV64qh-uyY
