### ISSUE TITLE
Windows installation bug

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Account-Manager#483]
![image](https://user-images.githubusercontent.com/8547538/99705099-23b7dd00-2a4e-11eb-91c2-de6ded79e2d6.png)

<img width="499" alt="Screen Shot 2020-11-19 at 10 01 13 AM" src="https://user-images.githubusercontent.com/8547538/99705149-303c3580-2a4e-11eb-84bb-56062cb55197.png">

**Comment by spconway** [comment]
Same issue and same console error on Windows 10 Home v2004 build 19041.630 using version 29 of alpha.

Possibly triggered by the following commit: b1e6235

working version of alpha (28) does not contain any migrations properties but the above commit looks like it added a migrations property which is causing it to hit a fail condition when it cannot find the projectVersion.

**Comment by charnysh-dev** [comment]
Solved at https://github.com/thenewboston-developers/Account-Manager/pull/484

**Comment by vkWeb** [comment]
@buckyroberts same issue here. Blank screen on starting the app.

PS: I am an old watcher of thenewboston, nice to see you back with such an amazing project :)
