### ISSUE TITLE
[Linux]The New Version TNB 29 web application icon can't display in Linux operating system.

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#485]
**Bug Description**
The application icon not displayed in Linux o.s

**Steps to Reproduce**
1. Go to "https://thenewboston.com/"
2. Click on 'Download Button'
3. Select Linux Tab 'Linux'
4. Click on Download for Linux Button
5. Make it executable File

**Expected behavior**
The application icon display in Linux machine

**Actual behavior**
The application icon not displayed in Linux machine

**Screenshots/Recordings**
https://prnt.sc/vmkzxb

**OS and Browser**
 - OS: [Linux]
 - Browser [ Chrome]

**Comment by buckyroberts** [comment]
Duplicate of https://github.com/thenewboston-developers/Account-Manager/issues/453
