### ISSUE TITLE
Able to give nickname that is very long

### ISSUE THREAD

**Issue by jamessspanggg** [thenewboston-developers/Account-Manager#494]
**Bug Description**
Currently, there are no limits for how long the nicknames can be (account, validator, bank, friend). Very long name shifts the buttons (3 dot button, send coins button) to the right.

**Steps to Reproduce**
1. Go to TNB account manager
2. Create a new account with a very long nickname
3. View that creation is successful and buttons are pushed to right

**Expected behavior**
The number of characters for the nickname should be limited, i.e. 64 characters?

**Actual behavior**
Able to create nicknames with any number of characters

**Screenshots/Recordings**
<img width="1520" alt="Screen Shot 2020-11-21 at 10 53 17 AM" src="https://user-images.githubusercontent.com/32864116/99865976-83e28680-2be8-11eb-9212-8043930039a3.png">

**OS and Browser**
 - OS: Mac, Chrome

**Additional context**
Do assign me this if this is a valid issue.

**Account Number**
c54c04774efaae20746fd3f29cdd619fea512e119bc1082b863572b2e8844104

**Comment by jamessspanggg** [comment]
@lapstjup would 64 character limit be reasonable for this? i.e. the same number of characters for the account number

**Comment by lapstjup** [comment]
@jamessspanggg I think it's a safe bet for now.
