### ISSUE TITLE
[Windows]_TNB_ver_30  How to make another validator as a primary

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#499]
**Bug Description**
no option to make another validator as a primary

**Steps to Reproduce**
1. Go to 'https://www.thenewboston.com/'
2. Download the web app
3. launch the TNB_ver_30
4. Click on validators "+" icon
5.Enter IP address
6.click on Add button
7.Repeat step 4
8.select another validator

**Expected behavior**
In right top right side corner three dots there should be options available for "set as primary validator"

**Actual behavior**
In right top right side corner three dots there not options available for "set as primary validator"

**Screenshots/Recordings**
https://prnt.sc/vo5lnd

**OS and Browser**
 - OS: Windows 10
 - Browser :Chrome, Safari

**Comment by buckyroberts** [comment]
PV is already auto set, not configurable by the user
