### ISSUE TITLE
[Windows]_TNB_ver_30 Same functions available for exit the application in navigation menu

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#501]
**Bug Description**
Same functions available for exit the application in navigation menu

**Steps to Reproduce**
1. launch 'TNB Account manager app'
2. Click on 'file' navigation menu
3. Click on 'Exit'
4. again launch 'TNB Account manager app'
5. click on Window
6. click on 'close'  

**Expected behavior**
Only one option available in navigation menu for Exit the app 

**Actual behavior**
For exit purpose in navigation menu 2 options are available 

**Screenshots/Recordings**
File->Exit https://prnt.sc/vo5vvh
window->close: https://prnt.sc/vo5wka

**OS and Browser**
 - OS: Windows
 - Browser Chrome

**Comment by buckyroberts** [comment]
No harm to have both. Closing for now.
