### ISSUE TITLE
[Windows]_TNB_ver_30 Search Functionalities Available For Transactions

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#502]
**Bug Description**
Search Functionalities is missing in Transactions side

**Steps to Reproduce**
1. launch 'TNB Account manager app'
2. Select any "my accounts"
3. Go to "Transactions Tab"

**Expected behavior**
In transactions Tab there should be search button available for find out any transaction  related detail

**Actual behavior**
Search functionality missing

**Screenshots/Recordings**
https://prnt.sc/vo59nh

**OS and Browser**
 - OS: Windows 10
 - Browser Chrome

**Comment by buckyroberts** [comment]
This involves setting up ElasticSearch for all nodes. We can possibly have this later but not now.
