### ISSUE TITLE
[Windows]TNB ver_30 Special symbols and blank space not allowed in my accounts 

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#506]
**Bug Description**

**Steps to Reproduce**
1. Launch the TNB manager app
2. Click on my accounts (+)
3. Select create new account
4. Give nick name "@#$%^^&  ^&*"
5. click on create button

**Expected behavior**
Doesn't allowed special symbols as a my accounts

**Actual behavior**
special symbols and blank space allowed as a my accounts

**Screenshots/Recordings**
https://prnt.sc/vo6jm8

**OS and Browser**
 - OS: Windows
 - Browser  Chrome

**Comment by buckyroberts** [comment]
Special symbols are fine for nicknames.
