### ISSUE TITLE
[mac] "bad seed size" if trying to add an existing account using account number

### ISSUE THREAD

**Issue by dstekanov** [thenewboston-developers/Account-Manager#508]
**Bug Description**
"bad seed size" if trying to add an existing account using account number

**Steps to Reproduce**

1. Install the TNB v30
2. Launch the app
3. Click on "My Accounts" (+ sign) on the left side menu
4. Select "Add Existing Account"
5. Enter any account number
6. Click "Add" button

**Expected behavior**
Seems we should provide a clear error under the "Signing Key" field about invalid signing key.

**Actual behavior**
"bad seed size" if trying to add an existing account using account number

**Screenshots/Recordings**
https://prnt.sc/voaayp

**OS and Browser**
 - OS: [Mac]
 - Browser [Chrome]

**Account Number**
a9a4823b71318bf481cf58f97fd3e8090c7221a84ae8ad25d8deff8922acfa8a

**Comment by angle943** [comment]
@dstekanov can you see if this issue persists with the latest changes? I tried replicating this using the account number you provided, but I did not encounter any issues

**Comment by angle943** [comment]
closing issue for now

**Comment by dstekanov** [comment]
Hi @angle943, I tried it with v(1.0.0-alpha.39) and cannot reproduce it anymore.
