### ISSUE TITLE
[Windows]TNB ver_30 Application Icon Not Displayed In Linux Operating System

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#509]
**Bug Description**
 Application Icon Not Displayed In Linux Operating System.

**Steps to Reproduce**
1. Go to "https://www.thenewboston.com/"
2. Click on 'Download Button'
3. Select 'Linux Tab'
4. Click On "Download For Linux" button

**Expected behavior**
Web App Icon supports All Operating System

**Actual behavior**
Web App Icon not supports Linux Operating System

**Screenshots/Recordings**
https://imgur.com/SiMDOwY.png

**OS and Browser**
 - OS: [ Linux]
 - Browser [ Chrome]

**Comment by buckyroberts** [comment]
Duplicate of https://github.com/thenewboston-developers/Account-Manager/issues/453
