### ISSUE TITLE
Transaction Time is not according to the current time-zone

### ISSUE THREAD

**Issue by YashovardhanSingh** [thenewboston-developers/Account-Manager#514]
**Bug Description**
When we see the time when the transaction occurred in the *Date Created* Section of the transactions tab, that time is not according to the current(your) time-zone.

**Steps to Reproduce**
1. Go to Transactions Tab
2. See the Date Created Section
3. See the Error

**Expected behavior**
The time should be according to the current time-zone.

**Actual behavior**
The time is not according to the current time-zone.

**OS and Browser**
 - OS: Windows 10

**Account Number**
38a99b8f1916eab0471ca1df26e7fe5e71d845e6ea5b233cd3d93a75097ea2d6

**Comment by angle943** [comment]
can someone verify that this is the case? We do convert it to your local time zone, so this is prob to do with your computer settings

**Comment by angle943** [comment]
duplicate issue #510
