### ISSUE TITLE
[Windows]TNB_Ver_30 Application not Responsive

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#516]
**Bug Description**
When Reducing Size Application in Windows TNB version 30 can't access other functionalities i.e. its not responsive

**Steps to Reproduce**
1. Launch the TNB version 30 app
2. Reducing the size of the application

**Expected behavior**
Web application its a Responsive all the operating system when reducing size its showing right sidebar and bottom sidebar

**Actual behavior**
Web application its a not Responsive all the operating system when reducing size its not showing right sidebar and bottom sidebar

**Screenshots/Recordings**
https://prnt.sc/vqagb2

**OS and Browser**
 - OS:Windows 10
 - BrowserChrome

**Comment by buckyroberts** [comment]
We decided not to worry about responsive design for now since this app can't be used on mobile. We are working on a mobile app for user who wish to use the network on their phones/tablets.
