### ISSUE TITLE
[Windows]TNB_Ver_30 Console Error web app

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#518]
**Bug Description**
Console Error 

**Steps to Reproduce**
1. Launch the Web app TNB VER _30
2. Click On Right Click Mouse
3. Click On Inspect Element
4. See The Console Error

**Expected behavior**
Doesn't have Console Error

**Actual behavior**
Console Error Shows in application 

**Screenshots/Recordings**
https://prnt.sc/vqak03

**OS and Browser**
 - OS: Windows 10

**Comment by jamessspanggg** [comment]
does this overlap with #517?

**Comment by buckyroberts** [comment]
Closing due to https://github.com/thenewboston-developers/Account-Manager/issues/517
