### ISSUE TITLE
Friend's Account says My Account Balance for the balance title and also does not display his nickname when we go to it through a transaction

### ISSUE THREAD

**Issue by YashovardhanSingh** [thenewboston-developers/Account-Manager#520]
**Bug Description**
When you go to the account of your friend via a transaction it displays the account number as the title instead of his nickname and also say's *My Account Balance*(as the title of the balance) instead of *Friend's Account Balance*.

**Steps to Reproduce**
1. Go to your friend's transaction
2. Click on his account number
3. See the Error

**Expected behavior**
The title should be his nickname and it should say *Friend's Account Balance*

**Actual behavior**
The title is the account number and it says *My Account Balance*

**OS and Browser**
 - OS: Windows 10

**Account Number**
38a99b8f1916eab0471ca1df26e7fe5e71d845e6ea5b233cd3d93a75097ea2d6

**Comment by angle943** [comment]
resolved with recent changes
