### ISSUE TITLE
Transaction not shown in my Account

### ISSUE THREAD

**Issue by nishp77** [thenewboston-developers/Account-Manager#521]
**Bug Description**

Just got this updated balance on my account as i completed the PR. However there's no transaction record for it.

**Steps to Reproduce**
No steps

**Expected behavior**
Should show us transaction history

**Actual behavior**
Does not show the up to date transaction history
**Screenshots/Recordings**

![image](https://user-images.githubusercontent.com/35785259/100533196-33aa8c00-31c7-11eb-801a-6f17536c2932.png)

![image](https://user-images.githubusercontent.com/35785259/100533204-4a50e300-31c7-11eb-808a-85ebb0856667.png)

**OS and Browser**
 - OS: Linux (Kubuntu)
 - Browser: Brave

**Additional context**

**Account Number**
c81061eb20ee1379ab98b6f5a125ebd0955278e36513eabd8d319967bb61d7e8

[How to Create an Account](https://thenewboston.com/account-manager/create-an-account)

**Comment by angle943** [comment]
I believe this has to do with changing the PV change, right? @buckyroberts 

If BE related, please close

**Comment by buckyroberts** [comment]
Yep, this is related to a BE issue that we are working on. Will be fixed soon.
