### ISSUE TITLE
[Win]TNB_Version_31 Notification Functionality Not Working 

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#524]
**Bug Description**
I Sending Coins from one account to another the receiver side can't gated notification about the received coins from someone.

**Steps to Reproduce**
1. Installing TNB Application 31
2. Select My Account 
3. Click on send coins button right side top corner
4. Select "TO" Account
5. Enter Coins
6. Click On Send Button
7. Now Go to Another Machine Friend 
8. See the Notification bell

**Expected behavior**
Nonfiction Alert msg shows when receiving coins from someone

**Actual behavior**
Nonfiction Alert msg not shows when receiving coins from someone

**Screenshots/Recordings**
https://prnt.sc/vsl09s

**OS and Browser**
 - OS:  Windows 10

**Comment by buckyroberts** [comment]
Due to missing CV services. Known design issue that we are working on. Closing.
