### ISSUE TITLE
[Linux]TNB_Ver_31_TNB Ver 31 The transaction Sequence always changed sometimes bank fee and validator fee top or bottom and sometime receiving amount will be top bottom or medium.

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#526]
**Bug Description**
TNB Ver 31 The transaction Sequence always changed sometimes bank fee and validator fee top or bottom and sometime receiving amount will be top bottom or medium.
(eg 1 1 10 , 10 1 1 , 1 10 1) like transaction history shows 

**Steps to Reproduce**
1. Launch TNB Ver 31 Application On Linux Machine
2. Click on 'Send Coins' Button
3. Select To Account
4. Enter Coins
5. Click On Send Button
6. Go to The Transaction Tab
7. Repeat The steps 3 To 6 (3 times)

**Expected behavior**
Follow One Format In Transaction History

**Actual behavior**
Always Changed In bank fee and validator fee received amount

**Screenshots/Recordings**
https://prnt.sc/vtavgl

**OS and Browser**
 - OS: [ Linux ,Windows]

**Comment by buckyroberts** [comment]
We are hiding Tx fees from this table soon so closing this ticket.
