### ISSUE TITLE
[mac]TNB_Ver_31 In Notification sender account displaying number instead of showing name 

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#527]
**Bug Description**
I am Transfer coins from mac to windows and go to the notification icon and click on senders name account in highlighted 
showing name of sender instead of showing account number even the in my friends account he's account exist

**Steps to Reproduce**
1. Launch TNB 31 application on mac
2. Add friend account 
3. click on send coins button
4. select account number "TO"
5. Enter Coins
6. Enter Send Buttons
7. Now go to the receiver account
8. click on notification bell icon top right side corner
9. click on sender name (e.g. in my case [mac]Original_account)

**Expected behavior**
In middle window showing account number instead of showing name of sender 

**Actual behavior**
In middle window showing account number

**Screenshots/Recordings**
https://prnt.sc/vu1eti	

**OS and Browser**
 - OS: [Windows 10,mac]

**Comment by angle943** [comment]
Resolved with the latest changes
