### ISSUE TITLE
Deleting account does not clears the transactions

### ISSUE THREAD

**Issue by YashovardhanSingh** [thenewboston-developers/Account-Manager#528]
**Bug Description**
After deleting an account the transactions of the account are not cleared and anyone can see them.

**Steps to Reproduce**
1. Delete an account with some transactions.
2. Login again or see it's transactions 
3. See the error

**Expected behavior**
Transactions must be cleared

**Actual behavior**
Transactions are not cleared

**OS and Browser**
 - OS: Windows 10

**Account Number**
38a99b8f1916eab0471ca1df26e7fe5e71d845e6ea5b233cd3d93a75097ea2d6

**Comment by buckyroberts** [comment]
Transactions remain on the blockchain. All Txs are public.
