### ISSUE TITLE
[windows]TNB_31 only sender side transactions recorded not receiver side transaction's recorded

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#529]
**Bug Description**
I am Sending coins from one account to another and I see that only Sender side transaction are recorded but Receiver End Transactions are not recorded but receiver gets a notification and update the balance only transactions tab records not shown it 

**Steps to Reproduce**
1. Launch TNB 31 Application on Windows 
2. Click on Send Button
3. Select TO Account
4. Enter Coins
5. Click On send Button

**Expected behavior**
The Transaction tab on both sides recorded transaction Sender and Receiver also

**Actual behavior**
Only Sender side Transaction is recorded and the receiver side transaction tab empty

**Screenshots/Recordings**
sender account screenshot:- https://prnt.sc/vur8v3
Receiver account screenshot:- https://prnt.sc/vurdms

**OS and Browser**
 - OS: [ Windows 10]

**Comment by angle943** [comment]
i believe this is a duplicate issue: #533
