### ISSUE TITLE
Initial connection logic

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Account-Manager#53]
After initial connection form is submitted, application should follow the logic described below, as well as store all data in redux.

**Bank endpoints:** 
- config - http://167.99.173.247/config

**PV endpoints:** 
- config - http://64.225.47.205/config
- banks - http://64.225.47.205/banks
- validators - http://64.225.47.205/validators
- account balance(s) - `/account_balance/<str:account_number>`

<img width="467" alt="Screen Shot 2020-07-19 at 6 57 47 PM" src="https://user-images.githubusercontent.com/8547538/87892397-d9681600-c9f1-11ea-8436-480fbd92fd66.png">

![Connect](https://user-images.githubusercontent.com/8547538/87881233-c5e68c00-c9ac-11ea-8838-8d71a72b1cff.png)

**Comment by kanishk-anand-oyo** [comment]
Picking this up
