### ISSUE TITLE
[Windows]TNB_ver_31 Same account number but transaction history different in different machines

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#531]
**Bug Description**
 Same account number but transaction history different in different machines

**Steps to Reproduce**
1. Launch TNB 31 version
2. Click on the My account + icon
3. Select Add Existing Account
4. Enter Signing key
5. Click on the add button
6. Go to other machines
7. Repeat step 1 - 5

**Expected behavior**
If the Existing account chosen then different machines same account number transaction history should be the same

**Actual behavior**
same account number Transaction history not the same

**Screenshots/Recordings**
 - 1 machine transaction history 
			- https://prnt.sc/vx76a6
 -  2 machine transaction history
			- https://prnt.sc/vx76yj

**OS and Browser**
 - OS:  Windows 10

**Comment by buckyroberts** [comment]
Known issue - working on syncing Tx histories.
