### ISSUE TITLE
[Linux]TNB_Ver_31 Validators Balance Lock Number Using as a Existing Account Number

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#534]
**Bug Description**
Validators Balance Lock Number Using as an Existing Account Number for creating an existing account number

**Steps to Reproduce**
1. Launch TNB Application
2. go to validators 
3. Select the Accounts Tab 
4. Copy Balance Lock Number
5. Go to my accounts
6. select "Add Existing Account" 
7. Paste Copied number in Signing Key 
8. Click on Add Button

**Expected behavior**
All Ready Usable number can't be used as a signing number

**Actual behavior**
All Ready Existing Account Number & Balance Lock Number using as a signing key for creating an account 

**Screenshots/Recordings**
https://prnt.sc/w2ws86

**OS and Browser**
 - OS:  Windows 10, Linux

**Comment by buckyroberts** [comment]
Intended behavior since there is no previous hash for brand new accounts.
