### ISSUE TITLE
Make `.test.ts` files be able to import with absolute paths

### ISSUE THREAD

**Issue by angle943** [thenewboston-developers/Account-Manager#548]
currently, our `.test.ts` files cannot understand what it means by `import {X} from '@renderer/...`. Change it to make it understand absolute paths.

**Comment by leelatanniru** [comment]
Account Number

7972e740622fe935bd7ce8b1ad3f0a0034888adbebf6bcc9e60d9d640cfc84db

**Comment by leelatanniru** [comment]
Hi @angle943 looks like I haven't received points for this bug. Could you please check.

**Comment by angle943** [comment]
@leelatanniru i've moved it over to `not paid` on the project board. The accountants should pay you now. let me know if you still don't receive it within the next week
