### ISSUE TITLE
Update overall style guide/colors

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Account-Manager#55]
Update the overall style guide/colors for the UI.

- replace color variables
- removed any old unused code/css

https://www.figma.com/file/xO8rfvp0INTni4gekeFTAt/Color-Test?node-id=8%3A1579

<img width="1336" alt="Screen Shot 2020-07-19 at 11 19 30 AM" src="https://user-images.githubusercontent.com/8547538/87881973-bddd1b00-c9b1-11ea-8b1b-439e969170ef.png">

**Comment by Hristijan95** [comment]
I am taking this

**Comment by angle943** [comment]
has been merged: https://github.com/thenewboston-developers/Account-Manager/pull/60
