### ISSUE TITLE
Configure SASS absolute path to be consistent with our other imports

### ISSUE THREAD

**Issue by angle943** [thenewboston-developers/Account-Manager#559]
Our absolute imports usually look like this:

`@renderer/containers/test.tsx`

In our sass files, to `@use` other modules, we currently have to do it like this:

![Screen Shot 2021-01-24 at 8 28 16 PM](https://user-images.githubusercontent.com/5943963/105661648-ce031500-5e82-11eb-8257-ce948f837369.png)

Configure our settings such that we can either:

1. import like `@use '@renderer/styles/layout'` to make it consistent with our other imports;

OR:

2. have the import start at `@renderer/styles`, so we just need to do `@use 'layout'`

**Comment by leelatanniru** [comment]
I have started working on this, will update the progress before 27th EOD.

**Comment by leelatanniru** [comment]
I made a PR for this, we can now import the module as @use 'layout'.
Please let me know if this is what we are expecting. @angle943

**Comment by angle943** [comment]
@leelatanniru ah oops, your PR actually worked. It was my Webstorm issue :(

I sent you 1000 coins :)

**Comment by leelatanniru** [comment]
Thank you 👍😊
