### ISSUE TITLE
Add friend

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Account-Manager#56]
- create the UI model element for adding friends
- on form submit, the friend object should be created and added to the redux store
- after friend object created, user should also be taken to the overview page for that friend

## Add Friend Modal
<img width="1198" alt="Screen Shot 2020-07-19 at 11 54 37 AM" src="https://user-images.githubusercontent.com/8547538/87882730-0945f800-c9b7-11ea-8469-12f3b0618bfb.png">

## Friend Overview Page (redirect them here after)
<img width="1142" alt="Screen Shot 2020-07-19 at 11 58 58 AM" src="https://user-images.githubusercontent.com/8547538/87882763-5033ed80-c9b7-11ea-82ca-9357a846efd0.png">

**Comment by Hristijan95** [comment]
I am on it - almost done, I forgot to comment.
