### ISSUE TITLE
[Feature Request] Search, Sort and Filter in Account Manager

### ISSUE THREAD

**Issue by itsnikhil** [thenewboston-developers/Account-Manager#569]
### Having a search, sort and filter functionality would be a great addition to transaction tabs
![image](https://user-images.githubusercontent.com/20350674/107376494-fa1fc680-6b0f-11eb-8c61-bf18cecc94b3.png)
### I believe Backend API is already available
 For example `http://BANK_IP_ADDRESS/bank_transactions?sender=<SENDER_ADDRESS>&recipient=<RECEIVER_ADDRESS>`

**Comment by angle943** [comment]
This is in our TODOs
