### ISSUE TITLE
Account Manager Icon

### ISSUE THREAD

**Issue by stweyel** [thenewboston-developers/Account-Manager#574]
The actual app icon seems a bit too big and doesn't fit into actual icon standards (at least on macOS).
I made a new one which meets the Apple design guidelines (well.. up to a certain amount, because even all apple icons don't follow them exactly). I'll provide more sizes if it'll be approved. 
https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon

Hope you like it!
![512px](https://user-images.githubusercontent.com/25363181/108220487-0ff84180-7137-11eb-84bb-1afb92f788b7.png)

Account Number
94161c7f2d143eb387aab95b1ee4d334df57a233a63bd466c8b2368148c4917d

**Comment by angle943** [comment]
I like, lets do it!

**Comment by stweyel** [comment]
Great! Here're the files.
[TNB Account Manager Icons.zip](https://github.com/thenewboston-developers/Account-Manager/files/6005079/TNB.Account.Manager.Icons.zip)
