### ISSUE TITLE
Account Manager UI update app wide

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Account-Manager#576]
- [x] Update how all long numerals appear on tables by displaying the first 6 and the last 6 of the numberals with '...' in between. For example for account number: 29fcs2...1kf8ws. Please make this update for all these columns listed. 
      - Sender
      - Recipient
      - Balance Key
      - Signature
      - Account Number
      - ID
      - Block
      - Block Identifier
      - Validator
      - Network ID
      - Root Account File Hash
      - Balance Lock
- [x] Update all font style to just use Inter, no more Jet Mono
- [x] Remove all horizontal lines on tables
- [x] Include hover state per each row, use color Gray 100 for hover state for now. 
- [x] Update all successful toasts to now just be one solid block of color making all text and icon white.  (Green 400). And update all thumbs up icon to the 'check-circle' icon.
- [x] Space between each column should be 16px.
- [x] Space between each row is 12px
- [x] Include the account nickname inside account number input when an account is selected in a dropdown.

Example design:
https://www.figma.com/file/YCHwuRMQy4oVqqVgk5fBxw/Bulk-Payment?node-id=0%3A1

**Comment by tomijaga** [comment]
Can I be assigned to this

**Comment by angle943** [comment]
@kristykjlee Hey Kristy, for this, are we getting rid of the expand/collapse?

![Screen Shot 2021-02-25 at 6 29 19 PM](https://user-images.githubusercontent.com/5943963/109246634-757faa00-7797-11eb-85e1-5a387ab9b52c.png)

If so, how can a user have access to the full string?

**Comment by angle943** [comment]
Due to new input components (toggle), i'll work on this
