### ISSUE TITLE
Balance not being displayed in top left corner in Account Manager

### ISSUE THREAD

**Issue by IanArb** [thenewboston-developers/Account-Manager#605]
**Bug Description**
My balance is not being displayed at the top left corner whereas it is showing in my account section. 

**Steps to Reproduce**
1. Switch from bank 54.193.31.159 where it was showing timeouts and wasn't getting balance shown for both
2. Switch active bank to 13.57.215.62
3. Go to my accounts section and balance is displayed
4. See that balance is not displayed at top left corner

**Expected behavior**
My bank balance should be shown in the top left corner as I would see in my accounts section.

**Actual behavior**
Bank balance is not being displayed in top left corner.

**Screenshots/Recordings**
![image](https://user-images.githubusercontent.com/6011914/111642151-c19d9780-87f5-11eb-963d-6fc1aa625fcc.png)

**OS and Browser**
 - OS: macOS Big Sur 11.2.1
 - Browser: N/A Desktop

**Additional context**
N/A

**Account Number**
d0ea7f5716c36ffa0300aa64424bb9dcdd7b9c6644577187309b67590e7dce55

**Comment by angle943** [comment]
this is a known issue: https://github.com/thenewboston-developers/Account-Manager/issues/582

to fix, just restart the app :)
