### ISSUE TITLE
No Discord UserName and GitHubUser name is shown after shaving.

### ISSUE THREAD

**Issue by Prawesh-MAGNETIC** [thenewboston-developers/Account-Manager#611]
**Bug Description**
When a registered user signs in, his/her  Discord UserName and GitHubUser name is shown after shaving.

**Steps to Reproduce**
1. Go to 'https://thenewboston.com/'
2. Click on 'Sign In'
3. Scroll down to 'input your registered  Email and Password'
4. See an error

**Expected behavior**
Registerd User  must see his : Display Name:
                                                Github Username:
                                                Discord Username:
                                                Account Number:
**Actual behavior**
But only His/Her Display Name and Account Number is visible.
**Screenshots/Recordings**

![Screenshot (112)](https://user-images.githubusercontent.com/71756108/113513731-b8981e80-9588-11eb-8bc1-2fac0abd7abf.png)
![Screenshot (113)](https://user-images.githubusercontent.com/71756108/113513733-b9c94b80-9588-11eb-9f07-c47fc4106cc7.png)

**OS and Browser**
 - OS:  Windows 10
 - Browser:  Chrome

**Additional context**

**Account Number**
b343d70bdc4bf593513bb30788b3c96f9ba2b78850534298c13d640c47832ecd

[How to Create an Account](https://thenewboston.com/account-manager/create-an-account)

**Comment by angle943** [comment]
closing for now. we are revamping the login/signup soon
