### ISSUE TITLE
AUTHENTICATION NEED FOR ACCOUNT MANAGER APP

### ISSUE THREAD

**Issue by bart-jay** [thenewboston-developers/Account-Manager#612]
Bug Description
There should be a defined need for proper authentication process where the desktop app prompt every user/account holder to authenticate correctly before one can access the UI of the app.

Steps to Reproduce
1. Go to the app and click to open
It opens just like that thus making the app's content which is the TNBC seem quite very valueless. The amount of coin should not even be seen without proper authentication.

Expected behavior
When the app is clicked to be opened, the app should prompt users to input a login ID, Maybe an option of mail and password or just a secret number to access the wallet. 

Actual behavior
The app doesn't prompt users for proper authentication process. It just opens which is not really safe and nice.

OS and Browser
 - OS: Noticed on Windows 10
 - Browser: app itself

Account Number:
1fe505773e03d268b9ff921302002aad999d801bdcc433e8513c7fe1799c06f4

**Comment by tomijaga** [comment]
This has already been suggested and has been planned by the front-end team
#579
