### ISSUE TITLE
Friends with coins  > 1,000,000 displays coins at 1,000,000

### ISSUE THREAD

**Issue by jamessspanggg** [thenewboston-developers/Account-Manager#620]
**Bug Description**
Not sure if this is intentional or not, but if a friend's account has 1,000,001, his account will be capped and displays 1,000,000.

**Steps to Reproduce**
1. Go to account manager
2. Add friend account 0fbd274ac9b151ce9e204fc607677e5ff65c2cec4c38b8da3d2797105af105fb
3. Observe that 1,000,000 is displayed but he/she owns more

**Expected behavior**
The exact amount should be displayed

**Actual behavior**
1,000,000 is displayed

**Screenshots/Recordings**
<img width="316" alt="Screen Shot 2021-05-22 at 9 42 22 AM" src="https://user-images.githubusercontent.com/32864116/119210962-04276d00-bae2-11eb-85c7-ecdfe6577bdf.png">

**OS and Browser**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari]

**Additional context**
Update: seems like the API is returning the 1,000,000 balance: http://54.219.183.128/accounts/efecc5a6fc27d880a468f0e92ba64c3b893b6f9ca5a0ab6480e7cf32bbfac588/balance

**Account Number**
Your account number where the reward coins for this bug bounty will be sent (pending review and approval).

[How to Create an Account](https://thenewboston.com/account-manager/create-an-account)

**Comment by AbhayAysola** [comment]
If the API is sending wrong info then it's not an issue with the account manager.
