### ISSUE TITLE
Send points modal

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Account-Manager#68]
Create modal where users are able to send points. The launch the modal, click on the "Send Points" button on the accounts page. The users (the senders) account will be preselected based on which account page they are currently on. However, the user will still be able to select a different account (if they have any). 

To send points, the user will create a block and send it to their active bank:

**Endpoints:**
- https://thenewboston.com/bank-api/blocks

**Figma mocks:**
- https://www.figma.com/file/M4wHv7B4JNig3bH2cywI9u/Accounts?node-id=46%3A2245

<img width="1270" alt="Screen Shot 2020-08-14 at 7 20 21 PM" src="https://user-images.githubusercontent.com/8547538/90303491-3c1ec700-de63-11ea-91be-d3dcf841d43e.png">

**Comment by Joe23232** [comment]
@buckyroberts Hey man how is it going. I just wanted to say I am a huge fan of your programming tutorials. By far you are the best YouTuber out there. Even other paid tutorials are inferior to yours. I do miss your tutorials a lot.
